### ISSUE TITLE
Race Condition in zerocopy `send()`

### ISSUE THREAD

**Issue by meawoppl** [zeromq/pyzmq#1006]
It looks like there is a race condition in zerocopy sends where closing the parent context in another thread can lead to a very confusing traceback.  

Functionally this is pretty unlikely, but it happens to us roughtly daily b/c we allocate/detallocate contexts something like a million times a day.  
```python
   File "/root/3scan/kesm/kesm/xact/sender.py", line 264, in sendPing
     transactor.send_multipart([b"PING"], description="Sending PING")
   File "/root/3scan/kesm/kesm/xact/TimedZMQTransaction.py", line 69, in send_multipart
     self._sock.send_multipart(parts, flags=zmq.NOBLOCK, copy=False)
   File "/usr/local/lib/python3.5/dist-packages/zmq/sugar/socket.py", line 368, in send_multipart
     return self.send(msg_parts[-1], flags, copy=copy, track=track)
   File "zmq/backend/cython/socket.pyx", line 636, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6954)
   File "zmq/backend/cython/socket.pyx", line 690, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6805)
   File "zmq/backend/cython/message.pyx", line 182, in zmq.backend.cython.message.Frame.__cinit__ (zmq/backend/cython/message.c:1835)
 'NoneType' object has no attribute 'underlying'
```

I am learning how the pyzmq GC works so I can help out on this.

**Comment by meawoppl** [comment]
This commit might fix this issue, but I am a little unclear what this new mutex is accomplishing.  
https://github.com/zeromq/pyzmq/commit/c1ea71c812d3ba21882bbddc29b42f7a3ed7a2b1

**Comment by minrk** [comment]
@meawoppl it may, but I would guess not. A similar error may occur on `_push_socket.underlying` instead. What's a bit peculiar is that it's the gc context that doesn't seem to exist, not the parent.  That should only happen during `atexit` process teardown, unless you are cleaning up the gc context explicitly. Are you sending messages at the end of the process immediately before it exits?

A design question: Is there a reason why the context is created and torn down on each send? It's generally advisable to use a single Context for the lifetime of a process, except in extenuating circumstances. The quickest way to do this is to use the global `zmq.Context.instance()` instead of `zmq.Context()`. Pooling sockets could be be even better, but not strictly necessary.

Given the size of your application and frequency of the error, I'm guessing the answer is no, but do you have an example that reproduces the error?

**Comment by meawoppl** [comment]
@minrk thanks for the quick response!  In writing this, I am realizing what a fairly complex system we have.  We are tearing down the context specifically.  We spawn a python process that:
Opens 5 ZMQ contexts, 4 of which call connect to 1 location, the 5th calls connect to all 4.
 Opens a contex

**Comment by meawoppl** [comment]
This is def. a race condition in a short-lived process.  I think the send_multipart() zmq_callback gc is pending while the interpreter is shutting down.  We are canning the subsystem that is responsible for most of our context create/deletes, but there is def. a lingering issue there.

**Comment by minrk** [comment]
closing this old issue because the error is in `cinit` and pyzmq backend no longer has `cinit`, so hopefully this issue is gone. Feel free to reopen.
