### ISSUE TITLE
Some messages lost when copy is True

### ISSUE THREAD

**Issue by mivade** [zeromq/pyzmq#1032]
I have defined a utility function to handle one-time messages which creates a new PUB socket and publishes a message, something like this:

```python
@classmethod
def broadcast(cls, ctx, message):
    socket = ctx.socket(zmq.PUB)
    socket.send_multipart([b'broadcast', message])
```

However, I find that as written above, subscribers that are listening to the `broadcast` topic never see these messages unless I change the last line to read

```
socket.send_multipart([b'broadcast', message], copy=False)
```

Presumably what is happening is the socket is getting garbage collected before the sending is actually complete. The question is *why* is this happening? It does not appear that the documentation clearly explains what is going on when I disable copying for sending.

For reference:

```
libzmq-4.1.6
pyzmq-16.0.2
Python-2.7.13
```

**Comment by guidog** [comment]
Obviously the code can't work.
Please post some working code that shows the problem.

**Comment by mivade** [comment]
Sorry, I obviously left out the connect part. Here is a full example demonstrating the problem:

```python
import time
from threading import Thread
import zmq
from zmq.devices import ThreadProxy

ADDRESS_IN = 'tcp://127.0.0.1:5558'
ADDRESS_OUT = 'tcp://127.0.0.1:5559'


class Broadcaster(object):
    @classmethod
    def make_pub(cls, ctx):
        socket = ctx.socket(zmq.PUB)
        socket.connect(ADDRESS_IN)
        return socket

    @classmethod
    def broadcast_without_copy(cls, ctx):
        socket = cls.make_pub(ctx)
        socket.send_multipart([b'broadcast', b'no copy'], copy=False)

    @classmethod
    def broadcast_with_copy(cls, ctx):
        socket = cls.make_pub(ctx)
        socket.send_multipart([b'broadcast', b'copy'], copy=True)


def listen():
    ctx = zmq.Context()
    sub = ctx.socket(zmq.SUB)
    sub.setsockopt(zmq.SUBSCRIBE, b'')
    sub.connect(ADDRESS_OUT)
    while True:
        if sub.poll(timeout=1000):
            topic, msg = sub.recv_multipart()
            print(topic, msg)


if __name__ == "__main__":
    proxy = ThreadProxy(zmq.SUB, zmq.PUB)
    proxy.bind_in(ADDRESS_IN)
    proxy.bind_out(ADDRESS_OUT)
    proxy.setsockopt_in(zmq.SUBSCRIBE, b'')
    proxy.start()

    thread = Thread(target=listen)
    thread.start()

    time.sleep(1)

    ctx = zmq.Context()
    Broadcaster.broadcast_without_copy(ctx)
    Broadcaster.broadcast_with_copy(ctx)
```

Output:

```
b'broadcast' b'no copy'
```

**Comment by minrk** [comment]
PUB sockets will drop messages if no subscribers are registered. Subscribers take a (small) finite amount of time to propagate subscriptions upon connection. The relevant bit here is that setting up the zero-copy bookkeeping has a nontrivial overhead, which delays the send just enough that the subscriptions have propagated before the first message is sent. copy is faster for small messages, so wins the race against the subscription setup, and the message is dropped.

Quick connect/send/close on a PUB socket is always going to drop messages. If you want to ensure delivery, a PUSH socket is probably a better fit. PUB sockets are designed in such a way that message loss ought to be acceptable at the application level.

Assuming your example is representative of your use case, I would change the proxy to be PULL-PUB instead of SUB-PUB, and change your broadcast sockets to PUSH. That way the connect/send/close of short-lived sockets will not drop messages, and PUB message dropping will only happen at the long-lived proxy, where presumably subscribers connect and disconnect less frequently. The proxy is the 'true' publisher, and the workers are delivering messages to it in a reliable way, rather than the proxy being a potentially transient subscriber to worker activity.

In general, I find that calling `connect` on a PUB socket is an indicator that PUSH might be the right choice. PUB rarely makes sense with one and only one subscriber (as opposed to zero to many).

**Comment by mivade** [comment]
Thanks for the explanation. In general, I am mostly using long-lived sockets, but added the class methods for cases where a one-off message is appropriate in my application.

I'm still seeing some dropped messages in another case even with PUSH-PULL when I have a convenience function which takes the socket and a message stub as parameters and calls `socket.send_multipart` on the modified message. Unfortunately I can't seem to reproduce this behavior yet in the above example even though in my real application I need to have `copy=False` for it to work.

**Comment by minrk** [comment]
copy=False doesn't have any effect on what libzmq APIs are called, it just sets up some extra bookkeeping, which can take a bit of extra time. Does your sender process perhaps exit immediately after sending? If so, do you explicitly close the socket and terminate the context? PUSH sockets won't generally drop messages except during aggressive shutdown of the process (or if LINGER is set to a too-small value).

**Comment by mivade** [comment]
Almost all sockets are long-lived, apart from the special cases (which I would like to rework to avoid them). It looks like the issue is in fact due to the non-zero time required to set subscription info: if I simply create and connect the subprocess's SUB socket before creating and connecting its PULL socket, this gives enough time to receive all messages that are sent early.

I'll close this, but would it make sense to add some further explanation to the documentation about what the copy argument is doing?

**Comment by minrk** [comment]
> would it make sense to add some further explanation to the documentation about what the copy argument is doing?

Sure. For now, I'll make a note here:

Ultimately, `Socket.send` results in `zmq_send` with a bit of memory pointing to the contents of the message. When `copy=True`, a `memcpy` is performed, copying the memory from Python to a buffer owned by zeromq. When `copy=False`, a pointer to the Python-owned memory is passed instead. Because libzmq io is async, some work needs to be done to ensure that Python doesn't free the memory before libzmq is done with it in the zero-copy case. pyzmq uses the `zmq_free_fn` hook to notify Python that libzmq is done with a given piece of memory. How exactly this is done has changed over time and shouldn't matter to the user. Hooking this up costs more than a small `memcpy`, so copy=False is more expensive than copy=True for small messages (up to at least tens of kB). So unless your messages are pretty large, copy=True is the way to go.
