### ISSUE TITLE
Current beta version does not install tornado via pip, causing import error

### ISSUE THREAD

**Issue by matthew-brett** [zeromq/pyzmq#1121]
Sorry for the slightly shoddy report but:

```
$ pip install --pre pyzmq
Collecting pyzmq
  Downloading pyzmq-17.0.0b3-cp35-cp35m-macosx_10_6_intel.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 7.4MB/s
$ python -c 'import zmq.eventloop'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/Users/mb312/.virtualenvs/test3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 18, in <module>
    import tornado
ImportError: No module named 'tornado'
```

**Comment by minrk** [comment]
Indeed, the tornado eventloop integration now requires tornado itself, rather than shipping a vendorized copy of the IOLoop. pyzmq in general does not need tornado, so it is not a dependency. Tornado is only a dependency when you are using pyzmq with tornado.

The same is true of other eventloop integration, such as `zmq.green` which requires gevent and `zmq.asyncio` which requires asyncio (if not in the stdlib).

Do you have a recommendation for how to better signal optional dependencies?

**Comment by matthew-brett** [comment]
No good recommendations on better signalling - I know that's a hard problem.

I bet I'm not the only person who hits this though.  Can you think of a way of warning people for a release cycle or two, so they can update their dependency files?

**Comment by minrk** [comment]
Hm. I can make a 16.0.x release with a DeprecationWarning. I should have done that in v14.0, which is when using minitornado became a fallback to real tornado.

I'll see if I can restore minitornado with a (visible) deprecation warning in 17.0. I'm not sure if the reworked eventloop integration will work, though.

**Comment by minrk** [comment]
I think #1122 restores minitornado with a warning, and #1123 backports the warning to 16.x
