### ISSUE TITLE
socket connect complete time

### ISSUE THREAD

**Issue by zsluedem** [zeromq/pyzmq#1125]
version:libzmq-4.2.2, pyzmq-17.0.0.b3

i bind a subscribe on a socket

```python
import zmq
c = zmq.Context()
s = c.socket(zmq.SUB)
s.bind("tcp://127.0.0.1:8877)
s.setsockopt(zmq.SUBSCRIBE, b'123')
s.recv()
```

then create a pub 

```python
import zmq
c = zmq.Context()
s = c.socket(zmq.PUB)
s.connect("tcp://127.0.0.1:8877)
s.send_multipart([b'123', b'3333'])
```

the subscribe is never `recv` because the `connect` operation is asynchronous if i am right.I have add a `time.sleep()` before `pub connect`.

Is there a better way to do this rather than adding `sleep`? I am not sure the sleep time is enough.

**Comment by minrk** [comment]
One bit of info that often comes up: if you are using zmq PUB/SUB, dropped messages *should be okay*. Recovery from or tolerance of lost messages should be handled at the application level.

If you only have a single subscriber, then using PUSH/PULL is typically more appropriate, as they don't drop messages.

There are two ways to notice if a PUB receives a subscriber. One is to hook up socket monitoring (`s.get_monitor_socket()`) and watch for subscribe events. Another is to use XPUB instead of PUB, which receives messages indicating subscribe/unsubscribe events.
