### ISSUE TITLE
Closed sockets reconnect.

### ISSUE THREAD

**Issue by CyrusTheVirusG** [zeromq/pyzmq#1143]
Running the following code produces an infinite reconnect condition when it should not, both sockets are closed. FIN-ACK is sent, but then it keeps trying to SYN infinitely.

    import zmq.green as zmq
    import socket
    import time
    import gevent
    
    hostname = socket.gethostname()
    local_ip = socket.gethostbyaddr(hostname)[2][0]
    
    context = zmq.Context()
    server = context.socket(zmq.ROUTER)
    client = context.socket(zmq.DEALER)
    server_port = server.bind_to_random_port('tcp://*')
    client.connect('tcp://{local_ip}:{port}'.format(local_ip=local_ip, port=server_port))
    poller = zmq.Poller()
    poller.register(client, zmq.POLLIN)
    poller.register(server, zmq.POLLIN)
    disconnect_at = time.time() + 5
    client_close_at = time.time() + 10
    close_client = False
    while True:
        events = poller.poll(timeout=1000)
        for event in events:
            socket, something = event
            print(event)
            print(socket.recv())
        tick = time.time()
        if disconnect_at < tick:
            if server:
                if not server.closed:
                    server.close()
                    poller.unregister(server)
                    server = None
        if client_close_at < tick:
            close_client = True
        if close_client:
            if client:
                if not client.closed:
                    client.close()
                    poller.unregister(client)
                    client = None
            print("Shouldn't be reconnecting.")
        gevent.sleep(1)
        if client:
            if not client.closed:
                client.send(b"Stuff.")

**Comment by minrk** [comment]
When underlying TCP connections are lost, zmq will automatically reconnect. That's what you are seeing. It's happening in this test case after you have requested that both sockets be closed because of the zmq LINGER option. Since you close the receiver before you close the client, there are undelivered messages waiting in the client's queue to be delivered when a server reappears. Calling 'close' on a zmq socket means: request that the underlying socket be closed once its pending messages have finished processing. It is an async request, not the actual closure of the underlying socket. LINGER provides a timeout for how long to wait on undelivered messages before discarding them. The default is -1, or forever. `ctx.term()` will block until all undelivered messages are delivered or discarded.

If discarding undelivered messages is okay for you, then you can either set linger when you create sockets:

```python
socket.linger = 1000 # 1000 milliseconds
```

or set linger when you close:

```python
socket.close(linger=3000) # give undelivered messages 3 seconds before discarding them
```

Either setting LINGER to a finite value or ensuring that all message are delivered will result in then underlying sockets being closed permanently.
