### ISSUE TITLE
Unknown event 16384 on monitoring socket

### ISSUE THREAD

**Issue by mrvn** [zeromq/pyzmq#1145]
I'm using the following code to map event numbers to names:

    EVENT_MAP = {}
    for name in dir(zmq):
        if name.startswith("EVENT_"):
            value = getattr(zmq, name)
            EVENT_MAP[value] = name
    ...
    event = zmq_monitor.recv_monitor_message(self._monitor, flags=zmq.NOBLOCK)
    event.update({"description": self.EVENT_MAP[event["event"]]})
    logger.debug(__("Event: {0}", event))

After updating zeromq and pyzqm yesterday this now fails with:

    KeyError: 16384

Event 16384 (0x4000) is defined in src/zmq_draft.h as

    #define ZMQ_EVENT_HANDSHAKE_FAILED_AUTH        0x4000

I have compiled neither zeromq nor pyzmq with any --enable-drafts option so I'm surprised that I would get a draft event from a monitoring socket. If zmq enables drafts per default then pyzmq should do so too.

**Comment by minrk** [comment]
How did you install libzmq? I believe libzmq enables drafts by default, but it may depend on context.

I would like to enable drafts by default in pyzmq to match libzmq, but since they are draft APIs, libzmq has promised to make breaking changes to them even in patch releases until they are promoted out of draft status. That makes the calculus different for whether pyzmq should support drafts by default from libzmq itself. libzmq supporting drafts by default means that downstream packages using the draft API should expect to be broken by any patch release of libzmq. I don't think that's an appropriate default behavior for pyzmq. But if pyzmq doesn't link the draft APIs

So your current choices are:

1. log/ignore unhandled event types (e.g. new events not yet known to pyzmq, or to you if you've included your own definitions for event constants)
2. build pyzmq with `--enable-drafts`
3. build libzmq with `--disable-drafts`

In general, I think 1. is the best choice, because it ensures your code is safe for a given pyzmq version even after libzmq is upgraded to promote constants out of draft status, or introduce new events. Neither of the other two make such a guarantee, as new releases of libzmq can always define new events and constants that pre-existing pyzmq releases can't know about.

**Comment by mrvn** [comment]
I'm building debian packages for libzmq and pyzmq. For this I (so far) always build a new libzmq and pyzmq package so I expect them to always match APIs. Especially autogenerated constants in pyzmq. I've changed it to enable drafts now so I get a consistent pair of debs.

For me I think pyzmq should match the settings libzmq has on compile. But I can see you concerns that the next libzmq version could break pyzmq without recompile. I recompile so that isn't an issue for me.

So I think pyzmq should by default half enable drafts. Thinks like the event constants for drafts would be save to enable. If they later change this would only break applications using the drafts api, which is expected but would not effect anyone else. Especially constants that stable functions like the monitoring socket will emit to unsuspecting downstream packages.

**Comment by minrk** [comment]
half-enabling drafts doesn't really work since it's a single flag at compilation time when you include zmq.h. But if you are mainly after the constants always being defined, I suppose we can copy over their definitions rather than load them at compilation time.

**Comment by mrvn** [comment]
I'm suggesting to add another option, e.g. --enable-safe-drafts, that would do exactly that and be the default. or --enable-drafts=safe although that would be unconventional.

**Comment by minrk** [comment]
That doesn't really work, though. If we switch to copying constants instead of loading them, I would make it unconditional to have fewer possible scenarios, rather than more.

**Comment by mrvn** [comment]
works for me.

**Comment by mrvn** [comment]
Any progress on this?

**Comment by minrk** [comment]
No, not immediately.
