### ISSUE TITLE
QT event loop integration

### ISSUE THREAD

**Issue by cowo78** [zeromq/pyzmq#1146]
Hi all
for an ongoing project I am using ZMQ pubsub and need to generate QT signals once a frame is received by a SUB socket. The basic idea is fairly straightforward and basic implementations can be found (i.e. https://gist.github.com/ivanalejandro0/dba1dd504edbc2c32e83): get the edge triggered filedescriptor and couple with a QSocketNotifier. This turns out in a ~100 lines implementation which I think it could be useful to many. Are you interested in integrating it into pyzmq? I would open a base pull request with the code that serves my purpose but I am of course interested in expanding and fixing it.

**Comment by minrk** [comment]
That sounds super useful! I would recommend making a standalone package, though. pyzmq is released somewhat infrequently and is a harder, compiled dependency since it pulls libzmq into wheels, etc. That means getting bugfixes for your piece of pyzmq is harder than if it's a standalone pure-Python package. I've been thinking of moving in this direction for the eventloop integration in zmq.green and tornado, since those are also pure Python, and it's a bit of a pain to have them in the same package as the base bindings.

**Comment by cowo78** [comment]
I would prefer not to have the usual one-man-toy-project package, which would likely lead to fragmentation and scarce user base. However the idea of factoring out eventloop stuff sounds good to me. If I can be of some help let me know.

**Comment by minrk** [comment]
Closing here, since this isn't going to happen in pyzmq, but can definitely be done in a standalone package.
