### ISSUE TITLE
Out-of-order message and slow performance when closing and reconnecting socket

### ISSUE THREAD

**Issue by will133** [zeromq/pyzmq#1171]
I have some code that would try to send a message, call close() and potentially reconnect again like the following:

```python
import threading

_NUM_MESSAGE = 1000


class ReconnectThread(threading.Thread):
    def __init__(self, ctx, server_url):
        super(ReconnectThread, self).__init__()
        self.ctx = ctx
        self.server_url = server_url

    def _get_new_socket(self):
        socket = self.ctx.socket(zmq.DEALER)
        socket.linger = 1000
        socket.connect(self.server_url)
        return socket

    def run(self):
        for i in range(_NUM_MESSAGE):
            sock = self._get_new_socket()
            sock.send_multipart([('blah_%s' % i).encode('utf8')])
            sock.close()


if __name__ == "__main__":
    import zmq
    ctx = zmq.Context()
    try:
        server_socket = ctx.socket(zmq.DEALER)
        server_url = 'tcp://127.0.0.1:7384'
        server_socket.bind(server_url)
        thread = ReconnectThread(ctx, server_url)
        thread.start()
        for i in range(_NUM_MESSAGE):
            print(server_socket.recv_multipart())
    finally:
        ctx.destroy()
```
First of all, I'd expect the message to be appear in order, but I'd get something like this instead:

```
[b'blah_0']
[b'blah_1']
[b'blah_3']
[b'blah_10']
[b'blah_7']
[b'blah_8']
...
```
Second, it seems like when linger is set to 1000 (1 second), it's not enough and the program would hang (since the message seems to be dropped).  I'd expect one second would be sufficient to send one (or even 1000 messages).  When I run this with a longer linger (say 5000 or 10000), it would terminate correctly, but the output sometimes would stuttered for a few seconds.

To me the behavior seems somewhat strange.  Does anybody explain to me why?  It makes the close() unreliable since I always set linger to be reasonable (to prevent the close() from hanging when there's message in the queue) and it's hard to set it correctly when this is happening.

I'm using pyzmq 17.0.0 with libzmq 4.2.5 running on Linux Python 3.6.5.

**Comment by minrk** [comment]
That behavior does seem a bit strange. I suspect this is a libzmq question, as pyzmq likely isn't involved much in the relevant behavior.

The main relevant fact for this behavior is that `sock.close()` is itself an async operation. It doesn't wait for LINGER messages to be delivered or dropped. Only `ctx.term()` blocks until LINGER is resolved. This means that your loop isn't creating/sending/closing sockets in each loop. At a lower level, the actual connection may not even be established until after `socket.close()` has finished and you have created and sent the next message. My guess is that it's not a matter of not being able to handle that many *messages* in such a short time, but rather not being able to handle that many *new connections*. I don't know if this is likely to be on the sender or receiver side or both (since they share a context).

This is also related to the ordering. libzmq makes no guarantee that messages coming from different sockets will be ordered (indeed, they will be fair-queued to avoid starvation). I imagine that when you start seeing messages appear out of order, that's when the connections have started getting backed up and there is more than one socket connected at once.

**Comment by minrk** [comment]
If you really want to create a socket, send a message, and block until it's done you can use a fresh Context for each:

```python
ctx = zmq.Context()
s = ctx.socket(...)
s.send(...)
s.close()
ctx.term() # this is where it blocks waiting for LINGER
```
