### ISSUE TITLE
import deadlock in pyzmq if used in another thread

### ISSUE THREAD

**Issue by confiq** [zeromq/pyzmq#1187]
If we have the following code
file1.py:
```python
import zmq
from threading import Thread
context = zmq.Context.instance()
socket = context.socket(zmq.PUB)
socket.connect('tcp://localhost:12345')
#socket.send_json('{uncomment_and_work:True}')
class importLock(Thread):
    def run(self):
        socket.send_json('{}')

a = importLock()
a.start()
```
and run it from file2.py

`import file1`
This will cause the deadlock in python. If we uncommon `send_json` before spawning new thread it will not cause deadlock. 

This is because of PR #721  and this [commit](https://github.com/zeromq/pyzmq/pull/721/files#diff-f838118f708bb4dea24b82532d851df1R451) that we import inside the function. 
Importing in function is bad practice and not [PEP8 ](https://www.python.org/dev/peps/pep-0008/#imports), this change can cause the deadlocks to clients and my suggestion is to remove it. 

I don't mind to open a new PR that will revert the change, but before that, I wanted to consult here and hear your opinion on the matter.

Cheers

**Comment by minrk** [comment]
I'm not necessarily opposed, but some of the statements here are inaccurate:

> Importing in function is bad practice

I'm not necessarily opposed to the change, but this statement is untrue. Delaying rarely used and/or costly imports until they are going to be used is a common and sensible optimization in Python. That said, these particular rarely-used imports probably aren't costly enough to be worth delaying, so I think it's probably sensible to put them back to simple top-level imports.

The real source of the problem here, though, is triggering the launch of threads on import. That's very strongly recommended against, and the cause of the deadlock. It is absolutely not a valid assumption in Python that calling a function cannot trigger imports. There are *lots* of ways for nontrivial logic, especially with threads, during imports to cause problems and hangs. The first thing to do is to move the thread-launching code in your `file1.py` module into a function so that it doesn't get instantiated on import. This is the right thing to do regardless of whether the pyzmq imports change. If your module is also a script, this is the reason the `if __name__ == '__main__':` idiom exists.

**Comment by confiq** [comment]
I agree with the most of the parts!
Our specific use-case is that we use pyzmq as `logging.handlers` module. 
We give that handler to other developers to use as they wish and that is beyond my control.

Another solution for this is to check if the import is locked (`imp.lock_held()`) and throw Exception if it is. But, considering that this is not heavy import, I'll make a PR with imports on top and let's start from there.
