### ISSUE TITLE
How can I install package pyzmq on windows

### ISSUE THREAD

**Issue by Rainiwinkler** [zeromq/pyzmq#1188]
When I tried to install pyzmq package in python, I always get this error message

PS C:\python37-32> pip install pyzmq
Failed building wheel for pyzmq
building 'zmq.libzmq' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visu
So I tried to fix it in two different ways: Option 1: I downloaded Microsoft Visual C++ 14.00 --> It doesn't work I downloaded the wheel "pyzmq-17.0.0-cp37-cp37m-win_amd64.whl" and tried to install it with the pip install comannd --> It doesn't work. And i also updated my setuptools.

Does anyone can give me an advice how I can install the package? That would be great.

**Comment by minrk** [comment]
There aren't wheels yet for Python 3.7, so you will need to install from source. I'm hoping to upload some in the next week or two. I'm waiting for [this issue](https://github.com/appveyor/ci/issues/2475) so that I can build the wheels on AppVeyor.

>  I downloaded the wheel "pyzmq-17.0.0-cp37-cp37m-win_amd64.whl" 

Where did you get a cp37 wheel for Windows? There isn't one on PyPI.

**Comment by minrk** [comment]
There are now wheels for cp37 on Windows
