### ISSUE TITLE
asyncio: await socket.recv() missing events

### ISSUE THREAD

**Issue by haverins** [zeromq/pyzmq#1203]
I encountered an issue where `await socket.recv()` sometimes does not resolve even though there are incoming messages. It does not seem to happen if traffic is low.

Minimal example to reproduce the issue: run following snippets (server.py & client.py). Client keeps printing messages for a while but then it stops. It seems that server is no longer notified by incoming messages thus run() is stuck at ```await router.recv_multipart()```. If 2nd client connects while server is stuck, then it starts receiving messages again but gets stuck again after a while.

```python
# server.py
import asyncio
import zmq.asyncio

async def send(router, identity, msg):
    router.send_multipart([identity, msg])

async def run():
    ctx = zmq.asyncio.Context()
    router = ctx.socket(zmq.ROUTER)
    router.bind("tcp://127.0.0.1:9001")

    while True:
        identity, msg = await router.recv_multipart()
        asyncio.ensure_future(send(router, identity, msg))

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

```python
# client.py
import asyncio
import zmq.asyncio

async def recv(dealer):
    while True:
        msg = await dealer.recv()
        print(msg)

async def run():
    ctx = zmq.asyncio.Context()
    dealer = ctx.socket(zmq.DEALER)
    dealer.connect("tcp://127.0.0.1:9001")

    asyncio.ensure_future(recv(dealer))

    count = 0
    while True:
        dealer.send(str(count).encode())
        await asyncio.sleep(0.001)
        count += 1

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

I'm using:

Python 3.6.0
libzmq 4.2.5
pyzmq 17.1.0

**Comment by haverins** [comment]
Update: I downgraded to pyzmq 16.0.4 and now everything seems to be working just fine.

**Comment by minrk** [comment]
There is definitely a bug. There are two bugs in your scripts, though: the send calls need to be awaited as well. Make sure to `await dealer.send` and `await router.send_multipart`. This doesn't fix the issue entirely, but it does improve the situation.

The bug is gone if you use `await send(router, identity, msg)` instead of `ansyncio.ensure_future(send(...)` in `server.py`. This suggests that the bug occurs when both an async send and recv are pending on the same socket, e.g. something along the lines of

```
start waiting for recv
start waiting for send
send happens
recv never wakes
```

**Comment by minrk** [comment]
Update: #1208 fixes this bug. Thanks for the test case!

**Comment by haverins** [comment]
Good to hear that it is fixed!

One question though: why is it necessary to await sends? I know they return futures but I don't really care _when_ they are resolved (in a case similar to my example which works fine without awaits using pyzmq 16.0.4).

**Comment by minrk** [comment]
> why is it necessary to await sends?

There's two kinds of awaiting sends. One is waiting for the 'real' underlying send. We don't do that, that's ~hidden by zeromq. What *is* async in pyzmq, though, is waiting for the `ZMQ_POLLOUT` state. This is rarely False, but can be in high traffic scenarios where HWM, etc. are being hit. If we didn't make these async, then there would be cases where `socket.send` would block. If we didn't have futures for these, then you couldn't catch errors like EAGAIN caused by SNDTIMEO being hit, etc.

Now, depending on your question, you don't have to `await` these futures, you could also `asyncio.ensure_future()` them. It's not important that *you* wait for them, just that they get registered with the eventloop. But if you want to catch possible errors raised in send, then you must await them.

**Comment by haverins** [comment]
Thanks for the detailed explanation. As far as I understand it's ok to not `await` or `asyncio.ensure_future()` if you know that send won't block or raise exception (depends on socket type and mode). This can be desirable if you want to reuse code outside asyncio (I've been using same zmq.PUB code in synchronous and asynchronous code). Otherwise it's probably best to be consistent and always `await` :)
