### ISSUE TITLE
zmq.PUB in zmq.asyncio is 7x slower than plain zmq

### ISSUE THREAD

**Issue by gammaguy** [zeromq/pyzmq#1209]
I was trying to rewrite my PubSub model with zmq.asyncio but it seems really slow vs plain zmq. 
Any thoughts?

This run was on Windows 10, Python 3.6.6, pyzmq 17.1.0 .
Also tried on AWS as Ubuntu 16.04, Python 3.6.5, pyzmq 17.0.0, relatively similar results

**Straight zmq:**
That took: 514.5178ms
Whole thing took: 568.4677ms

**zmq.asyncio:**
That took: 3788.8812ms
Whole thing took3936.3975ms

```python
# zmq_server.py
import zmq
from timeit import default_timer as timer
# import ujson as json
import json # took out the ujson as not everyone had it installed  but it's alot faster

def pub(num):
  port = "5556"
  context = zmq.Context()
  socket = context.socket(zmq.PUB)
  socket.bind("tcp://*:%s" % port)

  myList = ["AAA","BBB","CCC"]
  market = dict()
  market[myList[0]]=[100,10.00,10.01,200]
  market[myList[1]]=[200,10.00,10.01,400]
  market[myList[2]]=[300,10.00,10.01,600]

  start = timer()
  for i in range(num):
    channel = myList[i%3]
    messagedata = market[channel]
    jsoned_data = json.dumps(messagedata)
    socket.send_string(f"{channel} {jsoned_data}")
  print(f"That took: {(timer()-start)*1000}ms")

num = 100000
start = timer()
pub(num)
print(f"Whole thing took: {(timer()-start)*1000}ms")
```

```python
# zmq_asyncio_server.py
import asyncio
import zmq.asyncio
from zmq.asyncio import Context
from timeit import default_timer as timer
# import ujson as json
import json # took out the ujson as not everyone had it installed but it's alot faster

async def pub(num):
  port = "5556"
  context = Context.instance()
  socket = context.socket(zmq.PUB)
  socket.bind("tcp://*:%s" % port)

  myList = ["AAA","BBB","CCC"]
  market = dict()
  market[myList[0]]=[100,10.00,10.01,200]
  market[myList[1]]=[200,10.00,10.01,400]
  market[myList[2]]=[300,10.00,10.01,600]

  start = timer()
  for i in range(num):
    channel = myList[i%3]
    messagedata = market[channel]
    jsoned_data = json.dumps(messagedata)
    await socket.send_string(f"{channel} {jsoned_data}")

  print(f"That took: {(timer()-start)*1000}ms")

num = 100000
loop = asyncio.get_event_loop()
producer_coro = pub(num)

start = timer()
loop.run_until_complete(producer_coro)
print(f"Whole thing took{(timer()-start)*1000}ms")
loop.close()
```

**Comment by gammaguy** [comment]
Is the reason no one is responding is that this is an expected result?

**Comment by guidog** [comment]
Yeah, given how async works this is expected.
Figure out how the two examples differ wrt. to the send.
No need to keep that ticket open.

**Comment by guidog** [comment]
Can we close this?

**Comment by guidog** [comment]
As I said, figure out what the difference is.
What does the async send do (how does it work)?
What does the straight pyzmq send do?
Still no need to keep that ticket open.

**Comment by minrk** [comment]
There is a bit of extra work that the async implementation does to cooperate with async code, so I think it's always going to be slower. That said, there are likely optimizations that can be made to narrow the gap.

In particular, the async send, even if it's going to resolve immediately, checks `ZMQ_EVENTS` to see if it can send, and does some Future bookkeeping, then it has to check `ZMQ_EVENTS` again at the end, to make sure it doesn't starve events when dealing with zmq's unfortunate edge-triggered FDs.

You can see an immediate improvement if you use `send(bytes, flags=zmq.DONTWAIT)`. That changes the performance difference from ~9x to ~1.4x. That path is already optimized to resolve immediately, and triggers a lot less async overhead. #1215 optimistically takes the same optimized path every time, which makes sends that resolve immediately much quicker, at the slight expense of sends that would block, which relatively rare.

The remaining overhead is mostly in instantiating and managing Future objects. I'm not sure if there's a way to return a clone of a singleton FinishedFuture, since Future results are themselves not copyable. Maybe a mock awaitable object would work.
