### ISSUE TITLE
PyZMQ cannot receive messages outside Docker container.

### ISSUE THREAD

**Issue by NumesSanguis** [zeromq/pyzmq#1246]
I have a problem with a non-dockerized subscriber (bind) not being able to receive messages from a Dockerized publisher (connect). More details here: https://stackoverflow.com/questions/53802691/pyzmq-dockerized-pub-sub-sub-wont-receive-messages

Sorry if this is not the right location, but there are not that many people on Stack Overflow involved with both PyZMQ (ZeroMQ) and Docker. So I thought here was good for visibility.

**Comment by agn-7** [comment]
I had the same problem, you should use `tcp://*:xxxx` in the `.bind()` side instead of machine IP or localhost IP (`127.0.0.1:xxxx`).

Did you check [this](https://stackoverflow.com/a/53883117/3702377) and [this](https://stackoverflow.com/questions/51260058/how-to-expose-a-container-port-outside-of-docker-container-using-docker-compose) post?

**Comment by NumesSanguis** [comment]
Thank you, I managed to get it to work. I also got docker-compose to work for automatic IP inference between Docker-pyzmq modules: https://github.com/NumesSanguis/pyzmq-docker
