### ISSUE TITLE
pyzmq cannot be safely installed by EasyInstall

### ISSUE THREAD

**Issue by katiaGurtman** [zeromq/pyzmq#1277]
![Screenshot_20190330-101407_Termux](https://user-images.githubusercontent.com/22303179/55273016-9d79e080-52d6-11e9-836d-d6c7f5a4ade3.jpg)

**Comment by minrk** [comment]
easy_install has been [deprecated/recommended-against](https://setuptools.readthedocs.io/en/latest/easy_install.html) for several years, and I wouldn't consider it supported. Can you use `pip` instead? This looks like a bug in easy_install itself as well, since it's setuptools that is responsible for creating the .egg-info directory, not pyzmq.

**Comment by minrk** [comment]
Also check and make sure you have at least setuptools>=40.8 (`pip list`, `pip install --upgrade setuptools pip`)
