### ISSUE TITLE
Could bind_to_random_port range be [inclusive, inclusive]?

### ISSUE THREAD

**Issue by kinow** [zeromq/pyzmq#1280]
Hi,

We are using `pyzmq` in our project (for cyclic workflows) to replace our old communication layer, and it works like a charm, thanks!

In our project, we have a configuration option with a range for port binding, which matched well with `pyzmq`'s `bind_to_random_port`. However, yesterday we had [an issue](https://github.com/cylc/cylc/issues/3075) when running a workflow with a single port (useful for development & testing). 

We have [a fix](https://github.com/cylc/cylc/pull/3077) for our code in the works, which simply checks if we have a range for a single port. If we have a range with a single port, then we call `bind`, otherwise we can use `bind_to_random_port`.

That should work fine, but I thought perhaps it would make sense `bind_to_random_port` to use inclusive ranges? This way

```
bind_to_random_port(8080, 8081)
```

Would try to bind to 8080 and 8081. Right now when you want to bind to a single port, you have to use `bind`. When you want to bind to two ports or more, you have to make your last port one number higher to make your last port inclusive.

But in user interfaces in certain applications, when asked for a range of ports, I think it is more intuitive to ask for inclusive ranges.

Examples:

- Linux `sysctl net.ipv4.ip_local_port_range` uses inclusive ranges
- I believe `jupyterhub.utils.random_port` uses the port `0` to delegate to the OS finding a random port... in the case of using that with Linux, I believe that call is actually using the above inclusive range setting for the ports used
- Iptables' port range (e.g. `--sport 8080:8081`) is inclusive

I think in a workflow service, when a user is asked what range of ports to use for their tasks, they will think in an inclusive way. And when a used picks a single range 8080:8080 or a range with two ports 8080:8081, it would be nice to be able to use the same method in `pyzmq`.

I think the main issue would be backward compatibility in `pyzmq`, as users would be probably using the same approach when the range has a single port (i.e. call `bind`, or call range `min` and `max+1`) :disappointed: 

I understand this issue might be closed, but I thought if other users wanted similar feature, they would maybe comment later in this ticket :+1: 

Thanks for `pyzmq`!
Bruno

**Comment by minrk** [comment]
Thanks for the report and the references! I don't think we should change the behavior, though. The standard for ranges in Python is `[inclusive, exclusive)`, and I think that's the right pattern to follow in a Python API, rather than networking patterns in other contexts. The Python style has certain small advantages (e.g. `n, n+10` means 10 ports starting at n, not 11), but ultimately, there's ~no practical difference between inclusive and exclusive boundaries, so it's just a matter of getting used to whatever is chosen with the occasional +1 or -1, depending on your expectations. Changing it would cause a problem for every existing application using this API, which I don't think is worth it, even if I did agree that an inclusive range would be preferable.

**Comment by kinow** [comment]
>Changing it would cause a problem for every existing application using this API, which I don't think is worth it, even if I did agree that an inclusive range would be preferable.

All good :+1: 

Thanks!
