### ISSUE TITLE
send_multipart is not compatible with generator

### ISSUE THREAD

**Issue by hu6360567** [zeromq/pyzmq#1290]
```python
def encap_msg(msg):
    yield b'Procotol v1`
    yield uuid.uuid4().bytes
    yield from msg

socket.send_multipart(encap_msg(msg))
```
When I ran this snippet part of code, it raised an error.
```
File "xxxxxx/zmq/sugar/socket.py", line 439, in send_multipart
    for msg in msg_parts[:-1]:
'generator' object is not subscriptable
```

According to the document,  msg_parts is iterable, and generators are iterable.

**Comment by minrk** [comment]
You're right. it must be a sliceable iterable at the moment. We could cast other iterables to lists before sending.

**Comment by guidog** [comment]
Wouldn't that defeat the purpose of the iterator?

I'd rather change the API away from iterator in that case.
When sending messages you need to know how much you're sending anyway.

Another risk is the unbound nature of list(<iterator>).
You can't assert a given maximum size, hard to test...

**Comment by minrk** [comment]
Sometimes a generator is a more natural way to write the production of a sequence. I don't think there's any reason to worry about the theoretically unbound nature of iterators since send_multipart only makes sense with bounded sequences anyway. We are already iterating through the whole sequence before sending for type-validating purposes, so casting to a list inside send_multipart ought to be perfectly harmless. Right now, we require the user to `list(generator())`, or we could do it inside send_multipart. It doesn't make a big difference.

> According to the document, msg_parts is iterable, and generators are iterable.

I see [A sequence of objects to send as a multipart message.](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Socket.send_multipart), so it says a "sequence" not "iterable". Does it say "iterable" anywhere?

**Comment by hu6360567** [comment]
@minrk @guidog 
I was thinking that the generator may save the memory...

**Comment by jayrbolton** [comment]
What happened with this issue? I was using a generator to save memory and hit the same snag.
