### ISSUE TITLE
async socket.recv hangs and does not recieve messages

### ISSUE THREAD

**Issue by JonMontgo** [zeromq/pyzmq#1296]
Client:

```python
#
#   Hello World client in Python
#   Connects REQ socket to tcp://localhost:5555
#   Sends "Hello" to server, expects "World" back
#
import asyncio
import zmq
import zmq.asyncio

context = zmq.asyncio.Context()

#  Socket to talk to server
print("Connecting to hello world server…")
socket = context.socket(zmq.REQ)
socket.connect("tcp://localhost:5555")


async def send_req(request):
    print("Sending request %s …" % request)
    await socket.send_multipart([b"Hello"])
    print("Waiting for reply")
    message = await socket.recv_multipart()
    print("Received reply %s [ %s ]" % (request, message))


async def schedule_all():
    for i in range(0, 7000):
        await send_req(i)


if __name__ == "__main__":
    asyncio.run(schedule_all())
```

Server:

```python
#
#   Hello World server in Python
#   Binds REP socket to tcp://*:5555
#   Expects b"Hello" from client, replies with b"World"
#
import asyncio
import zmq
import zmq.asyncio

context = zmq.asyncio.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")


async def do_work(message):
    print("Received request: %s" % message)
    await asyncio.sleep(1)
    await socket.send_multipart([b"world"])


async def recv_loop():
    tasks = []
    print("starting loop")
    while True:
        message, _ = await asyncio.gather(
            socket.recv_multipart(),
            asyncio.gather(*tasks))
        print(message)
        tasks.append(do_work(message))


if __name__ == "__main__":
    asyncio.run(recv_loop())
```

Python 3.7.3
pyzmq==18.0.1

socket sending doesn't block and if you use a synchronous server to receive the event you will see that it receives the event generated by `await socket.send_multipart([b'hello'])`

**Comment by haverins** [comment]
I have no idea why, but it works for me if I replace `asyncio.run(recv_loop())`  with
```python
loop = asyncio.get_event_loop()
loop.run_until_complete(recv_loop())
```
and likewise for the client.

**Comment by JonMontgo** [comment]
yep @haverins your right. The issue seems to be with `asyncio.run()` being different than getting the event loop and runing until complete... I wonder what `asyncio.run` does different

**Comment by KrzysiekJ** [comment]
I’ve had a similar issue and the solution given by @haverins did indeed help. But without this comment, I would likely be lost. An average newbie asyncio user will probably not think about using event loops, since they are low-level API which he shouldn’t be required to deal with. Shouldn’t this issue be therefore reopened, to ensure that PyZMQ works with the canonical way of running asyncio applications?

**Comment by minrk** [comment]
I don't think this is a pyzmq issue. It's general to using `asyncio.run` when you've already instantiated active asyncio objects with the current loop. `asyncio.run` always creates a new, fresh eventloop:

```python
def run(main, *, debug=False):
    ...

    loop = events.new_event_loop() # <---- this ensures the current loop is replaced
    try:
        events.set_event_loop(loop)
        loop.set_debug(debug)
        return loop.run_until_complete(main)
    finally:
        try:
            _cancel_all_tasks(loop)
            loop.run_until_complete(loop.shutdown_asyncgens())
        finally:
            events.set_event_loop(None)
            loop.close()
File:      ...lib/python3.7/asyncio/runners.py
Type:      function
```

So you can use `asyncio.run` with pyzmq as long as you don't create globals attached to the existing loop first, which this example script does here:

```python
context = zmq.asyncio.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")
```

If these objects were created inside an e.g. `async def main()`, it would work as expected. That's how typical asyncio code is written.

So if there is anything to do for pyzmq, it would be:

1. to document that instantiating an asyncio object has a handle on the current event loop (common across asyncio-using libraries), or
2. lazily reference the current eventloop, so that the current loop is always used, and the same socket could end up hooked up to multiple event loops. I don't think we should do this, but I'm sympathetic to the idea that you haven't made any async *calls* yet, so why has it already grabbed the current loop?

Maybe we could defer the attachment to the current loop until the first async call?

**Comment by FrankJoy123** [comment]
I found the cause.
Say you init a zmq in a Thread-A at time T, and right now Thread-A holds a running asyncio Loop.
If later, you run THIS zmq agian, but with another asyncio Loop, it will behave unexpectedly.

That is, we need to ensure the running loop and the loop where zmq is first called(INIT LOOP) is always the same, meaning that we'd better using loop.run_forever to ensure the INIT LOOP persistent and always use it to hold the zmq.
