### ISSUE TITLE
socket.recv(flags=zmq.NOBLOCK)  always throws zmq error Resource temporarily unavailable

### ISSUE THREAD

**Issue by shivarajalagond** [zeromq/pyzmq#1320]
I have created simple client/server using pyzmq. One thing I am not sure is the recv() does not recive the message even though its been sent from server. It just ignores it and throws an error which I find to be strange unless my understanding of the behavior is wrong.

**Client.py**

```
try:
  socket = context.socket(zmq.REQ)
  socket.connect("tcp://localhost:2222")
  print("Sending request")
  socket.send(b"send the message")
  message = socket.recv(flags=zmq.NOBLOCK)
  print("Received reply %s " % message)
except Exception as e:
  print(str(e))
```

**Server.py**

 ```
context = zmq.Context()
 socket = context.socket(zmq.REP)
 socket.bind("tcp://*:2222")
 while True:
   message = socket.recv()
   socket.send(b"Ack")
```
I think the client should recieve the Ack and print it instead of throwing the exception.
The document says,
**With flags=NOBLOCK, this raises ZMQError if no messages have arrived**

Clearly the server is responding with "Ack" as soon as it receives the message.
The Error message is, Resource temporarily unavailable.

**Comment by kinow** [comment]
The [documentation](https://github.com/zeromq/pyzmq/blob/c4c9063e5d67d1c0b64e3b567e54c3facd8a274e/zmq/backend/cython/socket.pyx#L796) says

>        With flags=NOBLOCK, this raises :class:`ZMQError` if no messages have
>        arrived; otherwise, this waits until a message arrives.
>        See :class:`Poller` for more general non-blocking I/O.

And there is an existing issue that explains why it is designed that way: https://github.com/zeromq/pyzmq/issues/36

You can change your code slightly to make it work:

- **client.py**
```py
import zmq
import traceback
import time

context = zmq.Context()

try:
  socket = context.socket(zmq.REQ)
  socket.connect("tcp://localhost:2222")
  print("Sending request")
  socket.send(b"send the message")
  time.sleep(1)
  message = socket.recv(flags=zmq.NOBLOCK)
  print("Received reply %s " % message)
except zmq.ZMQError as e:
  if e.errno == zmq.EAGAIN:
    pass # no message was ready (yet!)
  else:
    traceback.print_exc()
```

-**server.py**
```py
import zmq

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:2222")
while True:
  message = socket.recv()
  socket.send(b"Ack")

```

Otherwise when you call the `recv` in a non-blocking way from your `client.py`, the server **may** not have sent the message yet, resulting in an error. Now, if you give some time for your server program to receive the message, and reply the Ack, then the client when receiving-non-blocking will get the right message. The output in my environment is:

```bash
$ python client.py 
Sending request
Received reply b'Ack' 
```

So I think it's working as expected, but you may have to adjust your code a bit.

**Comment by minrk** [comment]
Thanks for the explanation @kinow! That's exactly right. NOBLOCK means it won't block, and will instead raise EAGAIN if the event cannot be completed. You can also use `socket.events` to check if there are events to be processed.

**Comment by lchunleo** [comment]
is it possible to remove "Resource temporarily unavailable" from the terminal to make it "quiet" if we have handled the exception?

**Comment by minrk** [comment]
Yes, if you catch the Exception, you shouldn't see any messages in the terminal unless you print/log them.
