### ISSUE TITLE
MessageTracker broken for sending messages

### ISSUE THREAD

**Issue by manuelakuhn** [zeromq/pyzmq#1364]
Since pzymq version 17.0.0 the MessageTracker does not behave as descibed in the documentation anymore. When track is activated on a send, the MessageTracker done method always returns True even if no receiver is running. In version 16.0.2 this was still working correctly.

This behaviour could be reproduces on Debian 9 and Fedora 28 with Python 2.7, 3.5 and 3.6 with the following code snippet:

```python
from __future__ import print_function

import zmq
import time

def main():
    context = zmq.Context()
    socket = context.socket(zmq.PUSH)
    socket.connect("tcp://localhost:50300")

    print("using zmq version", zmq.__version__)
    print("using libzmq version", zmq.zmq_version())

    message = b"World"
    print("Send: ", message)
    res = socket.send(message, copy=False, track=True)

    if res.done:
        print("res: done")
    else:
        print("res: waiting")
        res.wait()
        print("res: waiting...")

    socket.close(linger=0)

if __name__ == "__main__":
    main()
```

Output for me:

**Version 16.0.2 works**
```
using zmq version 16.0.2
using libzmq version 4.1.6
Send:  World
res: waiting
^CTraceback (most recent call last):
  File "test/coding_tests/zmq_test/track_tests/run_track.py", line 27, in <module>
main()
  File "test/coding_tests/zmq_test/track_tests/run_track.py", line 21, in main
res.wait()
  File "/home/kuhnm/projects/hidra/virtualenvs/zmq_tests/local/lib/python2.7/site-packages/zmq/sugar/tracker.py", line 105, in wait
evt.wait(timeout=remaining)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
_sleep(delay)
KeyboardInterrupt
```

**17.0.0 -> broken**
```
using zmq version 17.0.0
using libzmq version 4.1.6
Send:  World
res: done
```

**18.1.1 -> broken**
```
using zmq version 18.1.1
using libzmq version 4.3.2
Send:  World
res: done
```

**Comment by minrk** [comment]
Short answer: an optimization is causing small messages to be sent as if with `copy=True` even when called with `copy=False`, and copied messages cannot be tracked. You can disable this optimization by setting `zmq.COPY_THRESHOLD = 0`.

A more "zmq way" to wait for peers would be to wait for a message from the peer, rather than trying to observe if a message is sent to the peer, which I would recommend if that's an option available to you.

## Long answer

MessageTracker doesn't directly track whether a message is sent, rather it tracks when libzmq is done using the shared memory buffer created with `copy=False`. Since libzmq sending is async and Python needs to know when libzmq is done with it, pyzmq has a garbage collection mechanism for making sure the Python interpreter doesn't free memory libzmq is still using (segfault), or application code doesn't overwrite it if it is an editable buffer (corrupted messages). This doesn't happen when `copy=True` because the buffer is not shared.

pyzmq 17 introduced `zmq.COPY_THRESHOLD`, a threshold below which messages with `copy=False` will actually be sent with `copy=True`, based on the fact that zero-copy is actually much *more* expensive for small messages than copying, due to the bookkeeping overhead (a small memcpy is pretty cheap compared to thread-syncing events). The result is that for small messages sent with `copy=False` below `zmq.COPY_THRESHOLD`, zmq is done with the shared buffer before the method returns and the corresponding tracker returned is also done immediately. The default value (64kB) is based on some testing, but is tunable by setting `zmq.COPY_THRESHOLD` for folks who want to do their own measurements.

This was introduced in pyzmq 17 becuase zero-copy is generally used as a performance optimization for large messages, but it is tedious in send (and impossible in recv) to pass `copy=False` only for the large frames at the application level. Doing it inside pyzmq with a global threshold is easier and makes the default behavior much more performant, and also is the only way to make it work for recv, because the size of the message to be received is not known beforehand.

**Comment by manuelakuhn** [comment]
Thank you very much for the detailed description and sorry for the late response. The workaround with `zmq.COPY_THRESHOLD = 0` works like a charm and for future projects this explanation helps a lot.
