### ISSUE TITLE
Windows wheels missing for Python 3.5-3.6 (pyzmq 19.0.1)

### ISSUE THREAD

**Issue by Tobotimus** [zeromq/pyzmq#1378]
Hi,

I just tried to install Jupyter Notebook on my Windows machine with Python 3.6 and got an unexpected error whilst trying to compile this library.

It looks as though the reason is, there's no wheel available for version 19.0.1 for Windows on Python 3.6 (or 3.5 for that matter). I'm not sure how they're deployed for this project and whether or not this is intentional, or a known issue. So I thought I'd ask :)

Regards,
Toby

**Comment by omry** [comment]
Same issue, I had to pin my CI config to 19.0.0 to work around it.

**Comment by minrk** [comment]
Takes a while for CI to upload the Windows wheels. They are up now. Thanks for checking!

**Comment by omry** [comment]
@minrk, can this be improved?
zeromq is basic infrastructure for many projects and this kind of delay can potentially fail many projects continuous integration.
This is not the first time that I have to spend time figuring out why my CI run failed only to discover that was because of pyzeromq installation issues.

**Comment by minrk** [comment]
Windows wheels are built on appveyor and uploaded manually. Uploading them automatically from CI would help a bunch, if you'd like to make a PR to appveyor.yml to add upload to PyPI.

A lot of the problem comes from building so many Windows wheels. Likely Python 3.5, at least, will stop being built at the next significant release. I hope to also stop building 32b Windows wheels for newer Pythons, which would cut the build number in half.

**Comment by omry** [comment]
Unfortunately I don't have the cycles to create this PR, but I hope it's something you would consider.
for now I pinned my own CI to a specific version so this is not going to be an issue for me for a while.

**Comment by minrk** [comment]
I don't either, so it likely won't be done until someone with time volunteers. I opened #1380 to track the task.
