### ISSUE TITLE
Lazy Pirate Pattern requires turning off LINGER but this isn't documented

### ISSUE THREAD

**Issue by basak** [zeromq/pyzmq#1396]
Hi,

I'm implementing the Lazy Pirate Pattern and found that I was running out of file descriptors if the timeout was short. Calling `socket.close()` didn't seem to be enough.

The [documentation example](http://zguide.zeromq.org/py:lpclient) calls `client.setsockopt(zmq.LINGER, 0)` first, and this resolved the problem for me. So that documentation is correct. However it took me a while to get this. Can I suggest that the documentation be adjusted to help prevent others from falling into this trap? It would help me, too, to understand the defined/expected behaviour around this too.

There's nothing I can find in the reference at https://pyzmq.readthedocs.io/en/latest/index.html suggests that this is required - so the only place that suggests it that I can find is in the Python code example. The [equivalent C documentationexample](http://zguide.zeromq.org/c:lpclient) uses `zmq_destroy()` instead and I don't see an exact Python equivalent of this. It's perhaps out of date now though? I see that `ZMQ_LINGER` is defined to be -1 (infinite) by default.

Expected "behaviour": somewhere in the definition of `zmq.Socket` the behaviour of construction, `close()`, `LINGER` and cleanup with respect to the requirement for OS file descriptors should be defined - especially because in the Python world, garbage collection is assumed.

**Comment by minrk** [comment]
I don't think there's anything to do on pyzmq docs, here. pyzmq doesn't do anything special and doesn't have anything related to the lazy pirate pattern. The Python example in the guid

**Comment by minrk** [comment]
It's not unique to pyzmq (on a quick read, at least [C++](http://zguide.zeromq.org/cpp:lpclient), [C#](http://zguide.zeromq.org/cs:lpclient), [go](http://zguide.zeromq.org/go:lpclient) and [ruby](http://zguide.zeromq.org/rb:lpclient) examples all set LINGER as is done in Python; czmq is the outlier which sets a different default LINGER from libzmq itself), so I would say it's the norm for all zmq use, not a pyzmq issue. But it does make sense to copy more of the docs for the underlying [zmq_close](http://api.zeromq.org/4-3:zmq-close) and [zmq_term](http://api.zeromq.org/4-3:zmq-term) to Socket.close and Context.term, respectively.

This would probably also be good to open an issue (or PR) on [the guide](https://github.com/booksbyus/zguide), since explanation of LINGER and term behavior with undelivered messages is a general issue with any pattern requiring discarding of messages, such as the lazy pirate. There aren't any message-pattern docs in pyzmq itself, that's all part of the guide.
