### ISSUE TITLE
If a socket is already waiting on close, context.destroy(0) blocks

### ISSUE THREAD

**Issue by mathieulongtin** [zeromq/pyzmq#1407]
If I run the following code, it stalls forever:

    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    socket.connect("tcp://localhost:12834")
    socket.send(b"hello")
    socket.close()
    context.destroy(0)

However, if I close the socket with `socket.close(0)`, it finishes right away.

It seems sockets that are already closing when destroying the context don't get force to close.

**Comment by minrk** [comment]
Destroy can only set LINGER on sockets that have not been closed, so calling close before destroy is explicitly leaving LINGER alone on the given socket. I don't think there's anything that can be done differently at the pyzmq level, since it's the documented libzmq behavior. If you want to set LINGER on close, you need to do it when you close the socket. That's either when you call `socket.close()` or when you close open sockets along with a context in `context.destroy()`, but can't be both.

Alternately, and probably better, is to set the appropriate LINGER when you *create* the socket so that it doesn't matter how it gets closed.

**Comment by mathieulongtin** [comment]
I'm fine with closing this since it's a documented behavior. At least next time I google this, I'll find this explanation :)
