### ISSUE TITLE
async recv hangs and nest_asyncio fixes it, buy why?

### ISSUE THREAD

**Issue by WestXu** [zeromq/pyzmq#1413]
```python
import asyncio

import nest_asyncio
import zmq.asyncio

nest_asyncio.apply() # (1)


ctx_ = zmq.asyncio.Context()
sub_ = ctx_.socket(zmq.SUB)
sub_.setsockopt(zmq.LINGER, 0)
sub_.connect("tcp://10.1.0.209:19999")  # Say this server simply never returns anything


async def recv():
    while True:
        try:
            sub_.setsockopt_string(zmq.SUBSCRIBE, "")
            print('Start recving')
            rsp = await sub_.recv_string()
            print('recved')
            print(rsp)
        except asyncio.CancelledError as e:
            print('Canceled', e)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.create_task(recv())
    loop.run_until_complete(asyncio.sleep(1))

```

This script runs and exits normally, printing only one line "Start recving".

Delete line (1), this script prints the same line as well but then hangs forever. 

I'm using pyzmq==19.0.2, on Ubuntu 20.04 LTS.

**Comment by minrk** [comment]
I'm not really sure what nest_asyncio does that changes things, but the hang on exit is because there are still references held on `sub_` at the global scope which prevents garbage collection from properly ordering the cleanup of context and sockets. Since `__del__` is not called, only the lower-level `dealloc`s are called, and the context is cleaned up before the socket, which means `term` and `close` can be called in the wrong order, resulting in a hang.

As always, explicitly closing and terminating your sockets ensures things are cleaned up properly, but I'll see if I can figure out a way to fix the implicit delete order.
