### ISSUE TITLE
zmq.curve_keypair() race condition on async/multi-thread environment

### ISSUE THREAD

**Issue by grishatsuker** [zeromq/pyzmq#1414]
Hey all, after further investigation, during the development a Benchmark project for my server, we've attempted to benchmark via the ZMQ connections using ZMQ.REQ and ZMQ.REP.

We have discovered that when creating multiple zmq.REQ Sockets with authentication - when each thread tries to access zmq.curve_keypair() to authenticate each socket on it's own, there was a race condition and all threads stated failing one after another.

When moving up the zmq.curve_keypair() and sending the result to all threads afterwards, it worked just fine.
(Still, using a "global" pair, this does not really reflect how clients normally act).

A) There's nothing in the documentation that provides information about this.
B) I suppose that this should actually be thread safe - I mean - why wouldn't this be?

Lots of blood and sweat have been lost when trying to make this work, thanks to this small function!

Thanks.

PS: May relate to this one: https://github.com/zeromq/pyzmq/issues/1402

**Comment by grishatsuker** [comment]
zmq.zmq_version()
'4.3.2'
zmq.pyzmq_version_info()
(19, 0, 0)
zmq.pyzmq_version()
'19.0.0'

**Comment by minrk** [comment]
I was surprised by this as well! There's certainly nothing in pyzmq that would make this not threadsafe, nor are there are any libzmq docs pointing to this fact, but there are [extensive comments in the source](https://github.com/zeromq/libzmq/blob/v4.3.2/src/random.cpp#L68-L96) about threadsafety pitfalls related to random number initialization. From my reading, it *looks* like they think the issue is addressed with locks, but that doesn't seem to be your experience. #1415 changes pyzmq to hold the GIL during these functions, which should serialize the libzmq calls. Can you test with that change?

**Comment by grishatsuker** [comment]
Sure - @minrk hit me up with an email whenever this is ready?

**Comment by minrk** [comment]
Can you try installing from #1415? (`pip install cython` needed to build from git):


```python
pip instal cython
pip install -v git+https://github.com/zeromq/pyzmq@refs/pull/1415/head
```
