### ISSUE TITLE
failed to install pyzmq on linux-alpine via pip

### ISSUE THREAD

**Issue by AminaDaoud** [zeromq/pyzmq#1457]
ERROR: Package 'pyzmq' requires a different Python: 3.8.6 not in '>=3.5'

```
FROM python:3.8-alpine

MAINTAINER Cowbell Team <cowbell@deezer.com>
ENV PYTHONDONTWRITEBYTECODE 1

# Install needed packages used to build image
RUN apk update && apk upgrade \
    && apk add --no-cache --virtual .build-deps \
               build-base gcc python3-dev musl-dev cyrus-sasl-dev \
               openssl-dev mysql-dev librdkafka-dev
RUN apk add zeromq-dev
```
i have the same when trying with Python 3.9.0
ERROR: Package 'pyzmq' requires a different Python: 3.9.0 not in '>=3.5'

**Comment by minrk** [comment]
Can you share how you are installing pyzmq itself and the output of the installation process? When I add `RUN pip install pyzmq` to the end of that Dockerfile, it works:

```dockerfile
FROM python:3.8-alpine

MAINTAINER Cowbell Team <cowbell@deezer.com>
ENV PYTHONDONTWRITEBYTECODE 1

# Install needed packages used to build image
RUN apk update && apk upgrade \
    && apk add --no-cache --virtual .build-deps \
               build-base gcc python3-dev musl-dev cyrus-sasl-dev \
               openssl-dev mysql-dev librdkafka-dev
RUN apk add zeromq-dev
RUN pip install pyzmq
```

gives

```
Successfully installed pyzmq-20.0.0
```

The output of `pip list` might be useful as well.

This error would mean that your installer is not properly interpreting the [Requires-Python](https://www.python.org/dev/peps/pep-0345/#requires-python) metadata field, but I believe pip has done that correctly since ~9.0.
