### ISSUE TITLE
convert .py to .exe with cx_freeze

### ISSUE THREAD

**Issue by Haninu** [zeromq/pyzmq#1494]
Hi, I tried to convert my .py to .exe with cx_freeze but it doesn't work, the error content is : 

```python
 File "C:\Users\HP\anaconda3\lib\site-packages\cx_Freeze\hooks.py", line 1325, in load_zmq
    libzmq = __import__("zmq", fromlist=["libzmq"]).libzmq
AttributeError: module 'zmq' has no attribute 'libzmq'
```

Is that someone who can help me to fix this, i may change something in hooks.py or add something !?

PS: I didn't touch any code on site-packages or changing something !

Thank you in advance

**Comment by minrk** [comment]
I think this is not an issue for pyzmq, it is an issue for cx_freeze.

Explicitly and unconditionally importing zmq.libzmq would be a bug. This module cannot be assumed to exist, and is only present when pyzmq is built with libzmq compiled as an Extension. This is often but not always the case on Windows. If this behavior changed for you recently, it is likely because you are using anaconda which builds pyzmq differently (and better) from a 'default' install.

In particular, anaconda pyzmq links libzmq as a shared dependency, and pyzmq 22 wheels from PyPI bundle libzmq in `pyzmq.libs` using delvewheel (like auditwheel for Windows).

My guess is that this should be in a try/except to handle libzmq being a regularly linked DLL, but I'm not sure that's enough since I don't know how cx_freeze locates DLL dependencies.
