### ISSUE TITLE
Pip install fails to get correct shared libraries 

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1511]
Hello :) 

I am using pip to install pyzmq. I select multiple OS targets like this

```python
dependencies ={'pyzmq':{'platform':{'Darwin':'macosx_10_9_x86_64', 
                                     'Win64':'win_amd64',
                                     'Linux':'manylinux1_x86_64'}
                                     },
                'distro':{'platform':{'any':'any'}}
                                     }
```

and then I run a script to install each one. 

```python
for dep_name, dep in dependencies.items():
            
            for os_name, platform_tag in dep['platform'].items():
                
                # ensure the right deps go in the right dirs :)
                if os_name != 'any':
                    parent_dir = os.path.join(lib_path, os_name, py_version)
                    
                else:
                    parent_dir = os.path.join(lib_path, os_name)
                
                #ensure each dependency has a valid directory to go into.
                os.makedirs(parent_dir, exist_ok=True)
                    
                if upgrade:
                    print("CR:Build | Dependency ", dep_name,
                          " for platform:", platform_tag, 
                          " and version: ", py_version,
                          " is being upgraded")
                    
                    print("CR:Build | Installing...")
                    proc = subprocess.Popen(
                    [sys.executable, '-m',
                     'pip', 'install',
                     '--target', parent_dir,
                     '--platform', platform_tag, 
                     #replace underscores as pip uses "37" not "3_7" for 
                     # major and minor versions of python
                     '--python-version', py_version.replace("_","",-1),
                     #default upgrade strategy is 'only_if_needed'
                     # see https://pip.pypa.io/en/stable/reference/pip_install/#options
                     '--upgrade',
                     '--progress-bar', 'pretty',
                     '--ignore-installed',
                     '--no-deps',
                     dep_name])
                    
                    #wait so that we can ensure the dependencies are actually there before
                    # we start installing them. A good e.g. of when synchronous makes sense!s
                    proc.wait()
```

This is currently done on a macOS system, and works for python 3.7 as, you can see, when it comes to linux, the correct shared libs are there.

<img width="668" alt="Screen Shot 2021-03-02 at 3 36 25 pm" src="https://user-images.githubusercontent.com/34228929/109598322-2bb70b00-7b6d-11eb-834f-e10968ee5250.png">

However, for python 3.8 and python 3.9, the shared libs are no longer for linux, but for darwin, the system I install these package on as you can see below

<img width="675" alt="Screen Shot 2021-03-02 at 3 39 54 pm" src="https://user-images.githubusercontent.com/34228929/109598550-8ea8a200-7b6d-11eb-9b64-45b7f0b43cc2.png">

Naturally this causes an import error and the resulting installation cannot be used, sad face.

I would very much like to have this fixed as I really enjoy being able to package for multiple OS targets on one machine! I also don't believe this was an intentional change, unless I missed something in the release notes :)

Best wishes

James

**Comment by Jeducious** [comment]
Also, forgot to add, windows works for 3.8 and 3.9, so it appears to be something peculiar to linux/darwin, linux cause that is what is broke, and darwin because i am on that OS, and spookily that is the shared libs that were put into the linux install.

**Comment by Jeducious** [comment]
I've just re-run my packaging scripts, linux builds on my machine :( the other wheels are just downloaded and installs, but the wheel for linux is built. Does this mean that I can no longer package for all OSes on one macOS?

**Comment by minrk** [comment]
I don't believe the command given is enough to do the necessary cross-compilation to *build* wheels for linux from macOS, so you shouldn't expect to get working results when it needs to compile pyzmq from source, i.e. when you ask for a wheel for a platform that isn't on PyPI. And there are not manylinux1 wheels for the latest pyzmq for Python >= 3.8. The latest wheels built for pyzmq with Python 3.8 and later target manylinux2010, not manylinux1, which is why your script isn't finding them.

Because it looks like you aren't attempting cross-compilation, you probably want to add `--only-binary pyzmq` (or `--only-binary :all:` for all packages) to make sure it only gets wheels and doesn't try to build from source, which won't work. If you add `--only-binary pyzmq` it will get the last manylinux1 wheel, which is pyzmq 20.0, and fail outright if no available wheel exists, which is better than successfully compiling a wheel that won't work.

I would also recommend switching your target platform to manylinux2010 or 2014 for linux, depending on what target platforms you are doing this process for. In general, you should use the latest-available tag that your target actually supports.  If the target platform satisfies e.g. manylinux2014 (CentOS 7 or later, i.e. not *extremely* old), it will find wheels built for manylinux2010 or manylinux1 (manylinux wheels are forward-compatible, but not backward-compatible).

If there's any change to make in pyzmq, it would be to fail hard in setup.py if it detects an attempt at cross-compilation, which will certainly fail.

**Comment by minrk** [comment]
Oops, didn't mean to hit close & comment, but I think I'll leave it closed as it's not actionable. Feel free to comment if you have further questions.

**Comment by Jeducious** [comment]
Hey man, no drama about the close, so long as there's nothing actually broken with pyzmq, I feel thats fair, maybe its pip that needs to sort this out? 

I was expecting that using pip as advertised would result in the correct package being installed, respecting the platform tag, but that's not what happened, so there's def something needing polishing, maybe even fixing. 

I also like your suggestion very much, I think failing when you can detect things will go wrong rather than signalling success is the right thing to do. I had no idea I had darwin so files in my linux packages! They've likely been there for a few months, happily being downloaded by goodness knows how many users. Our host application is still using python 3.7, which is fine. 

Finally, thanks a ton for those suggestions, I will be researching and testing them, and for anyone else who comes to this post later, and wondered as I did what manylinux they should use, there's a handy table [here](https://github.com/pypa/manylinux) which explains which tag to use for your distro of linux :)

**Comment by Jeducious** [comment]
Confirming setting --only-binary :all: works as expected, the proper linux shared libs are now ending up in my packages :) thanks!

Also, as you said, keeping manylinux1 means that my pyzmq version is stuck at 20.0.0
