### ISSUE TITLE
How is Context.__del__ being called?

### ISSUE THREAD

**Issue by ggggggggg** [zeromq/pyzmq#1512]
I have an issue where my program is hanging consistently at a certain point. Oddly, If I `ctrl-c`, it just prints out a zmq error and continues happily after that. It's hanging in `Context.__del__`, but what I can't figure out is how/why `Context.__del__` is being called. My code isn't calling it explicitly, and I haven't closed the context. I inserted a called to `traceback.print_stack()` in `sugar/context.py` inside the method `__del__` and I get the following traceback:

```  
  File "client.py", line 289, in _parse_packet_header_v10
    for name, p in zip(names1, params1):
  File "venv//lib/python3.6/site-packages/zmq/sugar/context.py", line 65, in __del__
    traceback.print_stack()
```
where `names1` and `params1` are lists of strings, so I don't see how `zip` or for loop based iteration would lead to calling `__del__`. Is this garbage collection or something else? Any ideas?

Based on a previous issue I've set `LINGER=0` for all sockets I open anywhere in my code, so even given that `__del__` is called I'm confused about why it is hanging.

**Comment by minrk** [comment]
`Object.__del__` is called when an object is deleted by the interpreter. Usually this happens when a variable goes out of scope, but can occur at very different times when there are cyclical references or other things that prevent that. Most often, it's called either when:

- a function returns, if the context is defined only within the function
- a parent object is deleted, if the context is an attribute on the parent
- interpreter shutdown, if not cleaned up elsewhere


For contexts in particular, `__del__` calls `term()` if term has not already been called. Per libzmq's specification, this will block until:

1. all associated sockets have been closed, and
2. all pending messages have been delivered (OR expired due to non-negative LINGER)

The most common cause of term hanging is failure to close sockets. *Usually* this is resolved by Python deleting dereferenced objects in topological order (sockets hold a reference to the context, context holds only weak references to sockets), but creating reference cycles in other objects can result in out-of-order deletion.

The fix is ~always to explicitly close sockets and contexts when you are done with them.
