### ISSUE TITLE
ZMQ Proxy(XPUB,XSUB) crashes, Docker container exit code 137

### ISSUE THREAD

**Issue by vankata-ashokkumar** [zeromq/pyzmq#1514]
I have noticed that creating many subscriptions(ex: 1M) leads to increased memory consumption on the proxy side. And after some time the container crashes with 137.

Here is the Proxy code.

```python

def main(lang):
    global context
    context = zmq.Context()
    frontend = context.socket(zmq.XPUB)
    frontend.bind("tcp://*:%s" % (8888,))

    backend = context.socket(zmq.XSUB)
    backend.bind("tcp://*:%s" % (9999,))

    try:
        zmq.proxy(frontend, backend)
    except Exception as e:
        print(e)

    frontend.close()
    backend.close()
    context.term()

```

Subscriber code 

```python

import zmq
import gc
import time

context = zmq.Context()


def subscribe():
    print "Adding new socket...."
    socket = context.socket(zmq.SUB)
    socket.connect("tcp://127.0.0.1:8888")

    import string
    import random  # define the random module
    letters = string.ascii_lowercase
    for b in range(1000):
        print "Sleeping for a second...."
        time.sleep(1)
        for bb in range(1000):
            topic = ''.join(random.choice(letters) for bb in range(30))
            print("subscribed to {topic}".format(topic=topic))
            socket.setsockopt(zmq.SUBSCRIBE, topic)

            print socket.getsockopt(zmq.EVENTS)
    print "Waiting for messages"
    i = 0
    for l in range(10):
        string = socket.recv()
        data = string.split()
        print data
        i = i + 1
        if i % 100 == 0:
            print "Collecting GC"
            gc.collect()
        time.sleep(0.01)
    socket.close()



```

Docker container ran with 1000M memory limit for the proxy.

Is this due to the MTrie at pub side?

**Comment by minrk** [comment]
I think this is a question for libzmq, since pyzmq isn't really involved in the proxy code other than setting it up and calling `zmq_proxy`. @bluca?

In gneral, it's also useful to provide a complete example. The publisher is currently missing.

**Comment by vankata-ashokkumar** [comment]
Hi @minrk , Please assume that the publisher is idle and not pushing any events. I have observed that when we add more subscriptions to the sub socket, the proxy consumes more memory with respect to the number of topics.

**Comment by bluca** [comment]
I have no idea what `137` means - you need adequate memory provisions according to the workload

**Comment by vankata-ashokkumar** [comment]
Thanks @bluca.

 If I have 100 subscriptions on SUB socket,Does the socket.close() remove the subscription from Pub socket? Or I have to socket.setsockopt(zmq.UNSUBSCRIBE, topic.encode('utf-8')) for each one of them before closing the socket?

**Comment by bluca** [comment]
they are removed automatically

**Comment by minrk** [comment]
137 is out-of-memory, so the implication is that 1M subscriptions of 30 bytes uses more that 1GB of memory. When I run this test with the proxy in a container and the subscriber in a different container, it's the *subscriber* that's using all that memory and not the proxy. The proxy stays below 20MB the whole time.

A subscriber does need to store all of its subscriptions in order to re-establish subscriptions on reconnect. In this case you have 1M random 30B subscriptions, so assuming there's no overhead whatsoever, you'd expect at least 30MB. Since you see more like 1GB, then the memory footprint of each random 30B subscription is closer to 1kB. I see this as well. The trie storage does seem relevant, because when I produce 1M unique subscriptions of similar size with a less random pattern, e.g. `f"{b:015}-{bb:015}"`, which gives subscriptions of the form '0000000000009999-0000000000008888' it only takes 60MB instead of 1GB.

**Comment by bluca** [comment]
tries are explicitly optimized for strings storage in terms of space and computation costs - if you have completely random bytes, then it's going to explode in complexity, that's pretty much expected - so again, it needs to be allocated enough resources

**Comment by vankata-ashokkumar** [comment]
@minrk I didn't have the container for the subscriber. I just ran the proxy in the container and noticed the memory increase. As @bluca mentioned it could be that the randomization of mine costed more memory.

**Comment by vankata-ashokkumar** [comment]
@bluca @minrk We are facing a ZMQ proxy crash every 3 days and when we look at the dashboards we don't see any CPU or memory spikes. From the code, we have gracefully handled the socket's initialization and termination.

And adding `socket.setsockopt(zmq.UNSUBSCRIBE, topic.encode('utf-8'))` before closing the socket seems helping us in this. Does the UNSUBSCRIBE helps in releasing any resources other than close() ?

**Comment by minrk** [comment]
ok, thanks for the info. Closing here.

**Comment by vankata-ashokkumar** [comment]
@minrk Could you please comment on the above query?

**Comment by minrk** [comment]
I can't really speak to any inner workings of libzmq. If you have questions, feel free to open an issue in libzmq. Since close is an asynchronous operation, it is possible there are unsent subscription messages being held up, which might be governed by LINGER. You could try `close(linger=0)` and see if that changes anything. That's just a guess.

**Comment by vankata-ashokkumar** [comment]
Thanks @minrk
