### ISSUE TITLE
aarch64 variant of the latest pyzmq from pypi comes with older version of libzmq

### ISSUE THREAD

**Issue by g4b1nagy** [zeromq/pyzmq#1522]
Installing pyzmq 22.0.3 on a `x86_64` machine gives me:

    >>> zmq.__version__
    '22.0.3'
    >>> zmq.zmq_version()
    '4.3.4'

while on a `aarch64` machine, I get:

    >>> zmq.__version__
    '22.0.3'
    >>> zmq.zmq_version()
    '4.1.4'

Not sure if this is intended (e.g. newer versions of libzmq cannot be easily compiled on ARM64) but it took me quite a while to figure out why my program was running fine on my laptop but not on a ARM64 machine.

**Comment by minrk** [comment]
This is intended, since that's the most recently available aarch64 build of libzmq [I could find](https://centos.pkgs.org/7/epel-x86_64/zeromq-4.1.4-6.el7.x86_64.rpm.html), and building libzmq again from source on arm isn't feasible with our CI.

If you can find a reasonably official CentOS 7-compatible (more precisely, [manylinux2014](https://www.python.org/dev/peps/pep-0599/)) RPM of more recent libzmq for aarch64, then it can switch.

If you want to rebuild pyzmq ignoring the current wheels on PyPI, you can add `--no-binary pyzmq` to your pip install. This should find an existing `libzmq-dev` package, if you have installed that with apt.

**Comment by g4b1nagy** [comment]
Because I'm not using `pip` directly, I wasn't able to use `pip install --no-binary pyzmq pyzmq`. That would have allowed me to use `libzmq3-dev` from the repos on the ARM64 device which currently stands at `v4.2.5`. Not perfect, but a step in the right direction.
In case anyone else runs into this, it was extremely easy (kudos to all the maintainers) to build the `pyzmq` wheel file on the ARM64 device directly:

    # Build and install libzmq
    git clone https://github.com/zeromq/libzmq.git
    cd libzmq/
    git checkout v4.3.4
    ./autogen.sh
    ./configure
    make
    sudo make install
    cd ..

    # Build pyzmq Python wheel
    git clone https://github.com/zeromq/pyzmq.git
    cd pyzmq/
    git checkout v22.0.3
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install setuptools wheel cython
    python setup.py configure --zmq=/usr/local/
    python setup.py bdist_wheel

    # Save wheel file and clean up
    mv dist/pyzmq-22.0.3-cp37-cp37m-linux_aarch64.whl ~/
    cd ..
    rm -rf libzmq/
    rm -rf pyzmq/

@minrk, thank you for the advice, I guess this can be closed now.

**Comment by minrk** [comment]
Glad you got something to work!

I think you should also be able to build your own local wheel from source with:

```
python -m pip wheel --no-binary pyzmq pyzmq
```

The same should work for just about any Python package.
