### ISSUE TITLE
os.add_dll_directory required on CPython 3.8 and later

### ISSUE THREAD

**Issue by zooba** [zeromq/pyzmq#1532]
I haven't done the historical work, but at some point this code below was added/changed.

It's not mysterious - conda-forge [has a patch](https://github.com/conda-forge/python-feedstock/blob/master/recipe/patches/0020-Add-CondaEcosystemModifyDllSearchPath.patch) to disable `add_dll_directory` and reenable finding DLLs on `PATH`. Because regular CPython does not have this patch, this change won't work in a range of scenarios where `PATH` is ignored.

So this needs the `add_dll_directory` call as well (or ideally, conda-forge would improve their patch, but I think that's unlikely right now).

https://github.com/zeromq/pyzmq/blob/b33873ca76a0d9d9ff9a959e78d26f1c25f9d29c/zmq/__init__.py#L65-L96

**Comment by zooba** [comment]
I see there's code higher up that ought to be doing the same thing. That makes this less urgent, but it does make this file pretty messy.

My other issues when I noticed this are covered by #1460

**Comment by minrk** [comment]
There are two ways libzmq can be 'bundled' with pyzmq:

1. externally built libzmq vendored in `pyzmq.libs` by [delvewheel](https://github.com/adang1345/delvewheel)/auditwheel/, in which case it is loaded as a regular DLL dependency of the backend, and
2. libzmq built by pyzmq itself as a Python Extension, in which case it's loaded via a simple `import`

Option 2 was how we did it on Windows for a long time time, and what happens when pyzmq is built from source with libzmq unavailable on the system (~never on Windows). 1. is generally preferable, and thanks to, delvewheel is how we do it now in almost all cases (I couldn't get it to work on Windows + PyPy for some reason, so that's the only remaining case where a pyzmq wheel bundles libzmq as an Extension).

Whatever advice you have for finding DLLs in `pyzmq.libs` that works consistently across Python versions and implementations would be welcome!
