### ISSUE TITLE
test_device_attributes flaky due to unclosed contexts and/or sockets

### ISSUE THREAD

**Issue by mattip** [zeromq/pyzmq#1536]
This test occasionally claims resources are still being held at teardown when the CFFI backend is active:
https://github.com/zeromq/pyzmq/blob/b33873ca76a0d9d9ff9a959e78d26f1c25f9d29c/zmq/tests/test_device.py#L23

It is basically
```
dev = devices.Device(zmq.QUEUE, zmq.SUB, zmq.PUB)
del dev
```

but [the error is confusing](https://github.com/zeromq/pyzmq/pull/1534/checks?check_run_id=2661637230#step:17:325): is the problem the exception when trying to close the resource or the fact that the test relies on garbage collection to release resources (in which case a more structured approach to closing the `Device` via a `dev.close()` or via a context manager may be needed)?

Copied from [this PR](https://github.com/zeromq/pyzmq/pull/1534#issuecomment-847599876), opening an issue so the subject does not get lost.

Perhaps PyPy should use the cython backend by default until this is fixed?

**Comment by minrk** [comment]
That test doesn't actually create any sockets or contexts, so calling `dev.close()` shouldn't do anything if the device hasn't been started because there's nothing to close. It is likely a previous test that's leaving stuff leftover, which I tried to cleanup in #1535.

> Perhaps PyPy should use the cython backend by default until this is fixed?

Failure to cleanup stuff like this across tests isn't an indication that the backend shouldn't be used by actual users, rather it's an indication that cleanup needs to be better in the test suite. Actual users shouldn't be affected by this, it's purely an issue with the tests themselves and not pyzmq in general.

**Comment by mattip** [comment]
Cool, thanks.

**Comment by minrk** [comment]
I _think_ this was fixed by #1540
