### ISSUE TITLE
L7 Load Balancing

### ISSUE THREAD

**Issue by florian-hoenicke** [zeromq/pyzmq#1564]
Hi 👋 
At Jina we are using zmq for connecting microservices https://github.com/jina-ai/jina.
When deploying the application on k8s, load balancing is only working on L4 (Network Layer).
Since we have long-living connections, the traffic is only getting routed to one instance.
Do you have some best practice guidelines when deploying zmq apps on k8s?

**Comment by minrk** [comment]
I think you'll have better luck asking on libzmq / checking out out [the guide](https://zguide.zeromq.org) (especially [load-balanced request-reply](https://zguide.zeromq.org/docs/chapter3/#The-Load-Balancing-Pattern). There aren't too many eyeballs on this repo, since it's just one language's bindings.
