### ISSUE TITLE
send_json does not accept copy=False as a keyword parameter.

### ISSUE THREAD

**Issue by nafisatd** [zeromq/pyzmq#1607]
I am  trying out this line of code. msg_details is a python dictionary.

`    sock.send_json(msg_details, copy=False)
`

I get the following error.

`  File "push.py", line 23, in <module>`

`  sock.send_json(msg_details, copy=False) `

`  File "/home/nafisa/.local/lib/python3.5/site-packages/zmq/sugar/socket.py", line 650, in send_json `

`    msg = jsonapi.dumps(obj, **kwargs)`

`  File "/home/nafisa/.local/lib/python3.5/site-packages/zmq/utils/jsonapi.py", line 40, in dumps`

`    s = jsonmod.dumps(o, **kwargs)`

`  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps`

  `  **kw).encode(obj)`

`TypeError: __init__() got an unexpected keyword argument 'copy' `

Anybody has any idea? Thanks in advance for helping.

**Comment by minrk** [comment]
If zero-copy is important to you, I would recommend custom serialization:

```python
serialized_msg = [json.dumps(msg).encode("utf8")]
socket.send_multipart(serialized_msg, copy=False)
```

rather that the basic `send/recv_json` methods.


It's true that zero-copy is unavailable for `send_json`. That's largely because zero-copy is meant to avoid in-memory copies when working with data structures like numpy arrays or existing buffers. Since `send_json` *necessarily* makes a copy of the input to serialize it, the flag is not available.

But there is also overhead to zero-copy: the bookkeeping of shared memory across threads is often more expensive than copying, unless messages are pretty large (at least 10s-100s kB).
