### ISSUE TITLE
"packet loss"-like behavior with simple PUSH/PULL configuration

### ISSUE THREAD

**Issue by kevincroissant** [zeromq/pyzmq#1671]
I am noticing what I can only describe as "packet loss" with a simple PUSH/PULL configuration when I send data very quickly in a loop. This is easily reproduced with two small scripts:

Producer:
```
import zmq
import numpy as np
import time
context = zmq.Context()
zmq_socket = context.socket(zmq.PUSH)
zmq_socket.bind("tcp://127.0.0.1:55555")

idx = 0
data = np.arange(120000, dtype=np.complex64)
while(idx < 1000):
    zmq_socket.send(data)
    idx = idx + 1
    print(idx)
    time.sleep(0.005)
print('done')
```

Consumer:
```
import zmq

sock = zmq.Context()
sock = sock.socket(zmq.PULL)
sock.connect('tcp://127.0.0.1:55555')

idx = 0
while(True):
    msg = sock.recv()
    print(f'idx: {idx}')
    idx = idx + 1
```

### **Test procedure:**
Using two terminals, run the producer and consumer. 
**Expected behavior:**
Producer outputs integers 0-1000, consumer outputs integers 0-999.
**Actual behavior:**
Producer outputs integers 0-1000, consumer outputs integers 0-999.

Now, comment out the `time.sleep(0.005)` line in the producer. Run both scripts again.
**Expected behavior:**
Producer outputs integers 0-1000, consumer outputs integers 0-999.
**Actual behavior:**
Producer outputs integers 0-1000, consumer only outputs integers up to ~500-800 (randomly varies). Example:
![image](https://user-images.githubusercontent.com/3029105/157793480-567072b0-26e0-40ee-a7b1-594adc896857.png)
Running it again:
![image](https://user-images.githubusercontent.com/3029105/157793552-73b738ae-0634-4db9-b660-2babec15efdb.png)

Is this expected behavior with PUSH/PULL when sending data very quickly? Perhaps the consumer is not keeping up, but my understanding is that libzmq will block on the producer side until the consumer is ready again. 

Thanks,
Kevin

**Comment by minrk** [comment]
Can you provide more context? (OS, Python, libzmq, pyzmq versions? How were pyzmq and libzmq installed?). Does it help to have an explicit close & term:

```python
sock.close()
ctx.term()
```

at the end of the script? Relying on garbage collection to do blocking cleanup _ought_ to work (and does for me when I run your test), but isn't the safest thing in the world. Explicitly closing sockets and terminating contexts ensures things wait until messages are delivered.

I can only get these scripts to run to completion and see no messages being lost (pyzmq 22.3.0, libzmq 4.3.4, macOS 12.2.1, Python 3.9.10)

**Comment by kevincroissant** [comment]
Debian Bullseye 11.2
Python 3.9.2
pyzmq 20.0.0 from pip
libzmq5 4.3.4-1 from Debian repos

I tried adding sock.close() and ctx.term() to the end of the scripts, and discovered even more oddities. Those two lines *do* fix the issue, but while testing it I tried doing a `time.sleep(1)` before the close() and term(), and found that just this sleep is enough to fix the issue. However, it's a sleep AFTER the loop:

```
idx = 0
data = np.arange(120000, dtype=np.complex64)
while(idx < 1000):
    sock.send(data)
    idx = idx + 1
    print(idx)
    #time.sleep(0.005)
print('done')
time.sleep(1)
#sock.close()
#ctx.term()
````
Perhaps the garbage collector is running during this sleep period? I'm not totally sure how that works in Python.

**Comment by minrk** [comment]
> I tried doing a time.sleep(1) before the close() and term(), and found that just this sleep is enough to fix the issue

Yes, I'd expect that, though how long the sleep needs to be will vary.

The issue is that zmq send is async - nothing has actually been sent when `sock.send` returns, it happens at an arbitrarily later point in time in a background thread. It's the _context_ that is responsible for all these async things. `ctx.term()` cleans up everything, and will not return until every message has been dealt with, either:

1. delivered, or
2. discarded as undeliverable (timeout governed by LINGER)

If the process exits without calling `context.term()`, any messages not delivered will be lost. pyzmq _tries_ to ensure that Python's garbage collection calls `context.term()`, but this is notoriously unreliable when the garbage collection is tied to process shutdown (e.g. global variables in a Python script). That's why adding a sleep works - if you wait until all the messages are delivered (happening in the background), there won't be any undelivered messages left to lose if `context.term()` isn't being called. But the right answer is to always close your sockets explicitly (just like files!). You can use sockets and contexts as context managers, like other resources such as files to make it easier to ensure they are cleaned up:

```python
with zmq.Context() as ctx:
    with ctx.socket(zmq.PUSH) as sock:
        ...
```

**Comment by kevincroissant** [comment]
Hi,

Thank you for your help on this. I appreciate your in-depth explanation. Properly handling the context and socket termination solved the issue I showed in this issue, and I have tracked down another (unrelated) bug that I was mistakenly blaming on this ZMQ issue. 

Thanks,
Kevin
