### ISSUE TITLE
zmq.auth.asyncio.AsyncioAuthenticator - enhancement proposal

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1729]
# Whats up?
The ability to avoid blocking the main event loop on I/O ops using python's asyncio lib is hugely important to our project. So is being able to verify if a connection attempt from a peer is one we are happy to allow. 

Currently we are using pyzmq's AsyncioAuthenticator to handle authenticating peers before allowing them to send/recv messages. However we've hit a problem. Turns out that [how zap messages are handled](https://github.com/zeromq/pyzmq/blob/58105c35394c3c13ec762965771daf2384e92df0/zmq/auth/asyncio.py#L40) doesn't allow for using await able callbacks, and this means we have to use a threaded version of the authenticator instead.

## In detail
The way we have currently setup our means of authentication is that we configure curve security using a [CredentialsProvider class](https://pyzmq.readthedocs.io/en/latest/api/zmq.auth.html#zmq.auth.Authenticator.configure_curve_callback) with a custom implementation of the callback method that queries a hierarchy of resources to check whether we `like` the public key of the peer that is attempting to connect. 

One of those resources is a web service, so we initially thought of using the AsyncioAuthenticator so we can be consistent with other queries to our same web service which also will be using asyncio. We had planned to design a service that would do this work and that the callback method would use that service. 

However we're now facing a split here since it became clear that the handling of callbacks in AsyncioAuthenticator doesn't actually treat the CredentialsProvider.callback method as an async method. It calls it as a normal method. So we cannot use our asyncio based web service to make queries about authentication. 

This is awkward to say the least as we either need to redesign the whole web query service, or have a different, special service for just the auth part. 

## What could be done
In my opinion, I see no reason why the callback method of the CredentialsProvider wouldn't be expected to do things like query databases, either locally or remotely. These seem like the very things asyncio was designed to cater for without blocking the main thread. 

I'd like to propose a PR that would enable two things;
1. Keep the existing API consistent with how it is now, so as not to break compatibility with anyone who's implemented using the AsyncioAuthenticator with a non-awatiable callback.
2. Insert a check to inspect if the callback is await able or not, if it is await able, then cause the AsyncioAuthenticator to await the result of the callback method of the CredentialsProvider so that it won't block the main thread/event loop. 

Having taken a look at the code, though it would take a smidge of refactoring, there don't appear to be any serious issues in implementing this as far as I can tell. 

## What I ask
A simple yes, go for it, or, no, and this is why not answer to my question of can we do a PR to fix this issue :)

**Comment by minrk** [comment]
Indeed, there's no reason it can't have an await [there](https://github.com/zeromq/pyzmq/blob/58105c35394c3c13ec762965771daf2384e92df0/zmq/auth/asyncio.py#L40). It just needs:

```python
r = self.handle_zap_message(msg)
if isinstance(r, Awaitable):
    await r
```

Allowing the credentials callback to be async is also totally sensible, but a bigger challenge, since that's called in a sync API, and that will need to be kept working. Adding async inside sync is always harder than allowing one sync call to be async inside an otherwise async API.

Honestly, I think the 'right' way to do this is to make the base implementation natively asyncio, and the thread implementation be running the asyncio version in a background thread. That's a bigger change, and might be a little tricky to get right in a fully backward-compatible way. I'll need to think about the implications of the blocking 'base' class.

I'm going to be on vacation for a while, so won't have time to work on this during the summer, but happy to see a PR!
