### ISSUE TITLE
monitor Event metadata is missing

### ISSUE THREAD

**Issue by shimondoodkin** [zeromq/pyzmq#1756]
Monitor Event metadata is missing.
I don't get source Address of connection/disconnection/handshake failed...
Am I correct?, or is there a way to get it

see "Event metadata" and example in:
http://api.zeromq.org/3-2:zmq-socket-monitor

but there is missing documentation about it is version 4
http://api.zeromq.org/4-2:zmq-socket-monitor

Event: {'event': 8, 'value': 13, 'endpoint': b'tcp://127.0.0.1:19580', 'description': 'EVENT_LISTENING'}
Event: {'event': 32, 'value': 33, 'endpoint': b'tcp://127.0.0.1:19580', 'description': 'EVENT_ACCEPTED'}
Event: {'event': 2048, 'value': 32, 'endpoint': b'tcp://127.0.0.1:19580', 'description': 'EVENT_HANDSHAKE_FAILED_NO_DETAIL'}
Event: {'event': 512, 'value': 33, 'endpoint': b'tcp://127.0.0.1:19580', 'description': 'EVENT_DISCONNECTED'}

**Comment by shimondoodkin** [comment]
Also i am not sure where to find it in the code.

**Comment by minrk** [comment]
Can you provide sample code? I suspect this is a libzmq question, not a pyzmq one, since pyzmq just passes through libzmq's own monitoring behavior.

From the doc you linked: 

> NOTE: in DRAFT state, not yet available in stable releases.

So you must at least make sure that you are using libzmq with drafts enabled (`zmq.has("draft")`).

**Comment by shimondoodkin** [comment]
I have posted two links the first one is of the legacy version 3. It contains an example code. And Also documentation.

I think in version 4 it is just a problem of documentation.

I think your indication about draft is incorrect.

In pyzmq I could not find the code that converts a c event struct into python dictionary.

**Comment by minrk** [comment]
> I have posted two links the first one is of the legacy version 3. It contains an example code. And Also documentation.

I don't see any links to pyzmq code that reproduces the issue you are seeing, which would help me understand what you are after. The libzmq 3 examples aren't especially relevant because pyzmq only supports events with libzmq 4.

> I think in version 4 it is just a problem of documentation.

I'm not so sure. The structure of event messages in libzmq 4 is [fundamentally different](https://github.com/zeromq/libzmq/issues/947), so this distinction matters. pyzmq only supports events with libzmq 4. There is no such thing as a `zmq_event_t` struct. In libzmq 4, event fields are delivered as message frames.

> I think your indication about draft is incorrect. Just click any stable version documentation. I don't have preference.

You mentioned the handshake failed event. From the [page you linked](http://api.zeromq.org/4-2:zmq-socket-monitor):

<img width="627" alt="Screen Shot 2022-09-07 at 13 00 37" src="https://user-images.githubusercontent.com/151929/188862664-551062c5-5e3c-4bd0-9908-52ad52a35ddd.png">

This may be unrelated to the key issue, though.

> 
> I meant that is something that is documented in a version 3. But not documented in version 4. And it exists in c but not in pyzmq.
> 

There's no such thing as event metadata in libzmq 4, the fields are delivered as message frames. I think that's why the documentation is different.

> In pyzmq I could not find the code that converts a c event struct into python dictionary.

It's [here](https://github.com/zeromq/pyzmq/blob/5dfeaafcc1ddb91c14644293df8b8c7d3171be2b/zmq/utils/monitor.py#L21-L50).
