### ISSUE TITLE
Unexpected Keyword Argument 'block'

### ISSUE THREAD

**Issue by Jabaker35** [zeromq/pyzmq#1877]
### What pyzmq version?

25.1.0

### What libzmq version?

Not sure

### Python version (and how it was installed)

Python 3.9.16

### OS

Windows 

### What happened?

I am currently working on a project where I am using JupyTab which is an open source Python library that allows me to directly connect my notebook to Tableau. Every time run it I keep getting the same issue. I have uninstalled then reinstalled as well as updated it and still nothing. I keep getting the same continuous issue every time I run the config file for jupytab. I am not too sure if anyone else had the same issue but it would be nice to know what I would need to do.

### Code to reproduce bug

```python
INFO: msg = client.shell_channel.get_msg(block=True)
INFO:TypeError: get_msg() got an unexpected keyword argument 'block'
INFO:[KernelGatewayApp] WARNING | Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x000001D127310400>
INFO:[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

**Comment by minrk** [comment]
Thanks for reporting, but this isn't a pyzmq issue, it's in whatever is using jupyter-client (likely not jupyter-client itself). `get_msg` is being called with an unsupported argument, [removed in 7.0](https://jupyter-client.readthedocs.io/en/stable/migration.html#zmqsocketchannel) (current is 8.2). The `could not destroy` message is also from jupyter-client because the client is being destroyed before stopping its channels.

The issues will be in whatever code is calling jupyter-client APIs, possibly JupyTab itself, I'm not sure.
