### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by gy-mate** [zeromq/pyzmq#2030]
### This is a pyzmq bug

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

26.2.0

### What libzmq version?

N/A

### Python version (and how it was installed)

3.12.5 installed via Homebrew

### OS

macOS 14.6.1

### What happened?

See https://github.com/microsoft/azuredatastudio/issues/25327 for details.

**Comment by minrk** [comment]
pyzmq has wheels for arm macs up to and including the upcoming Python 3.13. What version of pyzmq are you trying to install, and what is the output? There is no such information for macs in the linked issue, which is mostly about Windows, so there aren't any useful details there.

In the linked issue, all I see is someone trying to install pyzmq 24.0.1, which is too old for Python 3.12. Make sure you are installing `pyzmq>=25.1.1` for 3.12 support.

This works (arm mac, 14.6.1):

```
> brew install python@3.12
> /opt/homebrew/bin/python3.12 -m venv /tmp/testenv
> /tmp/testenv/bin/pip install pyzmq
Collecting pyzmq
  Downloading pyzmq-26.2.0-cp312-cp312-macosx_10_15_universal2.whl.metadata (6.2 kB)
Downloading pyzmq-26.2.0-cp312-cp312-macosx_10_15_universal2.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 31.9 MB/s eta 0:00:00
Installing collected packages: pyzmq
Successfully installed pyzmq-26.2.0
```

If you're getting a different pyzmq version, check what package is pinning it down, because that's the source of the problem, not pyzmq.

**Comment by gy-mate** [comment]
> In the linked issue, all I see is someone trying to install pyzmq 24.0.1, which is too old for Python 3.12. Make sure you are installing `pyzmq>=25.1.1` for 3.12 support.

Thank you very much, I think this is the issue!
