### ISSUE TITLE
BUG: PUB/SUB recv_multipart() gets incomplete messages after KeyboardInterrupt

### ISSUE THREAD

**Issue by aix-hmn** [zeromq/pyzmq#2044]
### This is a pyzmq bug

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

pyzmq-26.2.0

### What libzmq version?

libzmq-4.3.5

### Python version (and how it was installed)

Python-3.10.11 via conda-forge

### OS

Windows 10 x64

### What happened?

Hello everybody,
we are sending messages via PUB/SUB from a server to many clients. Each message consists of multiple parts.
If one of the clients is interrupted while waiting for message (e.g. a Jupyter Notebook and we press the interrupt-button), the cell interrupts as soon as the next message arrives. If we execute the cell again, it immediately returns a message, but with the first part missing.

To reproduce the behaviour:
In the code below, I have posted the code of all cells of the notebook which acts as a server and the cells of the notebook which acts as a client. I would have attached the notebooks directly, if it would be possible.
First execute the first cell of both notebooks. 
Then execute the second cell of the client-notebook, which waits to receive a message.
While it is waiting: Click the interrupt-Button of Jupyter to issue a KeyboardInterrupt.
Then execute the second cell of the server notebook, which sends a message containing 2 parts.
The client Notebook should now show the KeyboardInterrupt-Exception.
Execute the cell to receive a message again. The AssertionError will be raised, as only the second part of the message has arrived. 

Not sure if this is a problem with pyzmq or zmq itself. Or if it is even considered a bug.
What's the best way to handle it?
Is there a way to clear or to put back the partially received message?
Or do we have to handle it ourself by using an appropriate Exception-handler?

best regards,
Christian

### Code to reproduce bug

```python
# Server
### first cell to set everything up
import zmq
import time

zmq_context = zmq.Context()

# Send High WaterMark
zmq_context.setsockopt(zmq.SNDHWM, 1)
# Receive High WaterMark
zmq_context.setsockopt(zmq.RCVHWM, 1)  # should have no effect
# Clear old messages in pipe when closed
zmq_context.setsockopt(zmq.LINGER, 0)

zmq_context.setsockopt(zmq.SNDBUF, 1)
zmq_context.setsockopt(zmq.RCVBUF, 1)

zmq_socket = zmq_context.socket(zmq.PUB)
zmq_socket.RCVTIMEO = 10000
zmq_socket.SNDTIMEO = 10000

server_ip = "127.0.0.1"
port_number = 40000
zmq_socket.bind(f"tcp://{server_ip}:{port_number}")


### Second cell which sends a message
zmq_socket.send_multipart([
    b'a',
    b'b',
])



# Client
### First Cell to set everything up
import zmq
import json

zmq_context = zmq.Context()

# Send High WaterMark
zmq_context.setsockopt(zmq.SNDHWM, 1)  # should have no effect
# Receive High WaterMark
zmq_context.setsockopt(zmq.RCVHWM, 1)
# Clear old messages in pipe when closed
zmq_context.setsockopt(zmq.LINGER, 0)

zmq_context.setsockopt(zmq.SNDBUF, 1)
zmq_context.setsockopt(zmq.RCVBUF, 1)

zmq_socket = zmq_context.socket(socket_type=zmq.SUB)
zmq_socket.RCVTIMEO = 10000
zmq_socket.SNDTIMEO = 10000

server_ip = "127.0.0.1"
port_number = 40000
zmq_socket.connect(f"tcp://{server_ip}:{port_number}")
zmq_socket.setsockopt_string(zmq.SUBSCRIBE, "")


### Cell that receives a message
try:
    data = zmq_socket.recv_multipart()
except (zmq.Again) as ex:
    print("Again", ex)
else:
    print(data)
    assert len(data) == 2, f"len was only {len(data)}"
```

**Comment by minrk** [comment]
It's not a libzmq issue because the libzmq recvs are probably completing, but if you interrupt while only part of a message has been received, the rest will still be waiting to be received.

A case could be made that this is a bug in recv_multipart, but if so, I would think just about every socket library in Python would have the same one, and I don't really know how to go about making it robust except for registering signal handlers, and that should really be something applications do, not libraries. There's no way to tell where in the stack an interrupt will raise, so data might be received but not recorded. Any statement in C or Python could be the one that is interrupted.

> Is there a way to clear or to put back the partially received message?

Put back's not really feasible, but 'clear' should be fine if you're okay dropping the interrupted message. `socket.rcvmore` will be True if a multi-part message has been started but not completed. So to flush a possible partial message, you can do:

```python
if socket.rcvmore:
  # partial message received, flush it and discard the partial message
  print("flushing partially received message")
  socket.recv_multipart()
# proceed to full recvs
msg = socket.recv_multipart() # will always be a whole message
```

You could put that in an `except KeyboardInterrupt:` block, or before you start receiving, depending on how you want to handle it.

An alternative is to register a signal handler that prevents SIGINT while you are receiving. But I'm guessing if you are interrupting receives, that's because you _want_ to be interrupting receives.

**Comment by aix-hmn** [comment]
Thanks for the reply. 
`socket.rcvmore` helped a lot. We put it into an exception handler as suggested and it works. Thanks.

Should this ticket stay open, in case you want to fix something inside the library or can I close it?

best regards,
Christian

**Comment by minrk** [comment]
I think we can close it. I don't think there's much we can do robustly, so this discussion is probably all the resolution we are going to get. We can always come back later.
