### ISSUE TITLE
ZBeacon Support

### ISSUE THREAD

**Issue by whitmo** [zeromq/pyzmq#423]
I'd love to use ZBeacon from the python bindings, but have no idea how to add it.  Filing this ticket to learn more!

**Comment by dkrikun** [comment]
IMO, zbeacon is a very useful, independent (of czmq/pyczmq) protocol, and it should be implemented directly in pyzmq. See NetMQ beacon for example, cool stuff :smile:.

**Comment by minrk** [comment]
I agree that implementing it in Python is probably a good idea. I would however suggest that it be implemented outside pyzmq, and then consider upstreaming it into pyzmq after it turns out to be sufficiently valuable, popular, stable, and useful for that to be appropriate.

There's minimal cost to it being a separate package, especially if it's pure Python, and binding it to the pyzmq relatively slow release cycle wouldn't be beneficial.
