### ISSUE TITLE
Symbol not found: _zmq_errno

### ISSUE THREAD

**Issue by dionyziz** [zeromq/pyzmq#581]
One of our OpenBazaar users is facing this issue:

https://gist.github.com/inexile14/bc38be40ba02b68c504f

I'm running the exact same pyzmq version (pyzmq==14.3.1) with no problems.

Please advise?

**Comment by caitdeen** [comment]
Hv the same issue:  

```
Undefined symbols for architecture x86_64:
      "_zmq_errno", referenced from:  ..... "
```

Using virtualenv, and python 3.4. Solved installing universal binaries on system python from here:

```
$ brew install zeromq --universal
```

**Comment by leofang** [comment]
Hello,


I also have the same issue and the same result when running `otool` and `nm` commands as @sindhus. I installed pyzmq 14.6 against the system python (python 2.7 in OS X 10.10.3) using `sudo easy_install pyzmq`. I googled a lot and found people always recommend using Homebrew or other distributions such as Canopy Enthought on Mac. Is there no way around it?

Thanks.

**Comment by minrk** [comment]
@leofang there appears to be a problem with the old-style eggs for 14.6. I recommend using `pip` instead of easy_install. I'll disable the eggs while I figure it out.

**Comment by minrk** [comment]
I also strongly recommend against using the System Python on OS X unless you are exclusively using virtualenvs.

**Comment by leofang** [comment]
Hello @minrk,

A few seconds ago I just realized that `pip` works, and then I saw your comment! Thanks.

For people having the same issue: do `sudo easy_install pip` to get `pip` installed, then remove any existing pyzmc by `sudo pip uninstall pyzmc`, and finally do `sudo pip install pyzmc`. My system python now can find pyzmq by `import zmq` in the python environment. 

@minrk, one more dumb question: why the system python is not recommended? I am not sure I understand what a "virtualenv" is...

**Comment by minrk** [comment]
The System Python on OS X is used for system functionality, and it can be problematic to install things with it. There are a variety of issues, including security problems. System Python is not kept up to date, and is frequently broken for one reason or another.

[virtualenv](https://virtualenv.pypa.io/en/latest/) is a tool for isolating installation of Python packages so they don't interfere with each other. Using these avoids some (not all) of the problems with OS X System Python. If you don't know what it is, I probably wouldn't recommend using it, because it can complicate managing installation.

I typically recommend [conda](http://docs.continuum.io/anaconda/install.html) to novice Python users on OS X and Windows, especially those who want to use scientific packages. Or you can get Python.org binaries from [the website](https://www.python.org/downloads/) or [brew cask](http://caskroom.io/). Or you can install Python with [Homebrew](http://brew.sh/).

**Comment by sharmalakshay93** [comment]
Hi, having the same issue. Running "jupyter notebook" gives me the following error:

```
Lakshays-MacBook-Pro:~ lakshay$ jupyter notebook
Traceback (most recent call last):
  File "/Users/lakshay/anaconda/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/Users/lakshay/anaconda/lib/python3.5/notebook/notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
  File "/Users/lakshay/anaconda/lib/python3.5/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/lakshay/anaconda/lib/python3.5/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/Users/lakshay/anaconda/lib/python3.5/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/Users/lakshay/anaconda/lib/python3.5/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/Users/lakshay/anaconda/lib/python3.5/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/lakshay/anaconda/lib/python3.5/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/Users/lakshay/anaconda/lib/python3.5/zmq/backend/cython/constants.so, 2): Symbol not found: _PyInt_FromLong
  Referenced from: /Users/lakshay/anaconda/lib/python3.5/zmq/backend/cython/constants.so
  Expected in: flat namespace
 in /Users/lakshay/anaconda/lib/python3.5/zmq/backend/cython/constants.so
```
