### ISSUE TITLE
Unicode: send_multipart/recv_multipart and ZMQStream

### ISSUE THREAD

**Issue by davidblewett** [zeromq/pyzmq#725]
According to https://zeromq.github.io/pyzmq/unicode.html#what-this-means-for-pyzmq:

> Still, we recognize the fact that users will quite frequently have unicode strings that they want to send, so we have added socket.<method>_string() wrappers.

However, there is no corresponding syntactic sugar for the send_multipart / recv_multipart socket methods, nor is there a mechanism for auto handling encoding for ZMQStream. In the former case, it would be nice to mimic the send/recv handling and provide send_multipart_string / recv_multipart_string wrappers. For the latter, it might be easier to provide an encoding argument to on_recv/on_recv_stream that defaults to `None`. If it's not `None`, automatically decode each field with the given character set before passing it to the handler.

Without these, things get annoying very quickly on Python 3.

**Comment by minrk** [comment]
I don't think adding `recv_multipart_string` is a particularly good idea, especially since things like ROUTER prefixes aren't going to be strings. Instead, what I think might be preferable is a generic `deserialize` hook for turning a zmq message, which is by definition a sequence of binary blobs, into a Message, as defined by the application. This seems to be the norm for how zmq is used, and it would probably be nice to build it in. One such deserializer could be `lambda msg: [ frame.decode('utf8') for frame in msg ]`, which would be your recv_multipart_string.

In most of my applications, messages are some kind of object or a dictionary, and the application provides a library function `send(socket, msg)` that only ever calls `socket.send_multipart([buffers])`, and the function does all the serialization/deserialization necessary.

**Comment by davidblewett** [comment]
I do like the idea of a hook. I generally use a namedtuple to represent a message, with primary fields as distinct frames. For more complex messages, the last 2 fields are generally a JSON or protobuf string, and an indicator what serializer was used.
