### ISSUE TITLE
Performance Improvements for Asyncio

### ISSUE THREAD

**Issue by achimnol** [zeromq/pyzmq#859]
To decide whether I should migrate my codes from [aiozmq](https://github.com/aio-libs/aiozmq) to the vanilla pyzmq, I have created a benchmark based on the examples here: https://github.com/achimnol/asyncio-zmq-benchmark , using a single-process push/pull (producer/consumer) pattern via a local TCP socket.

The result shows that aiozmq performs better than pyzmq.
Both the pyzmq and aiozmq internally uses poller based on `zmq_poll` to implement custom asyncio event loops, but the performance of aiozmq is a way better and aiozmq allows the event loop replaced with different implementations such as [uvloop](https://github.com/MagicStack/uvloop).
I suspect that PyZMQ's frequent context switching due to an extra poller and send coroutines may be causing severe performance penalties, though we need more detailed profiling results.

Would be there some ways to improve this?

**Comment by minrk** [comment]
To use alternate polling implementations, a raw FD must be used (i.e. the zmq.FD API), but given the unusual way zmq.FD behaves, I don't want anything in pyzmq to rely on it (zmq.green does this, and is why I hope never to do it again). There are good performance reasons to do so, which is why it's AOK for aiozmq to do it this way, but I would prefer not to use it in pyzmq, for now. There may be other things that can be done to improve the pyzmq performance, though.

I'm hoping for libzmq to introduce a standard level-triggered FD API, in which case pyzmq could do away with its reliance on zmq_poll. But I've been pushing for that for years now, and there doesn't seem to be anyone with the time, interest, and expertise to work on it, so I've mostly given up on that.

I opened a PR against your benchmark repo that doubles the performance of the pyzmq benchmarks because there is an extra, redundant poll in the pyzmq examples that is not in the others, doubling the runtime of those tests.

I also made a performance optimization in #860, which gives the following results from your benchmarks (after my PR removing redundant poll):

```
asyncio + aiozmq: 0.348208 sec.
tornado + aiozmq: 0.422775 sec.
uvloop + aiozmq: 0.187043 sec.
zmqloop + pyzmq: 0.170215 sec.
tornado + pyzmq: 0.167461 sec.
```

**Comment by achimnol** [comment]
Yes, now I understand that ZeroMQ abstracts the underlying OS sockets (e.g., ZeroMQ does not expose the peer address because individual peer identity is not the focus of its abstraction; just the ability to distinguish different peers is sufficient.) and FD may work differently. That's why I was at first confused with #857. My prior try to improve the event loop compatibility in #857 used it blindly.

+1 for standardized level-triggered FD API. It would make the adaptation to the event loop easier.

Q: Is there particular reasons limiting the support for different asyncio event loop implementations (e.g., uvloop)? According to your performance improvements, I wonder how fast it can be with such "faster" loop implementations. Is it possible to plug-and-play different event loop implementations with `zmq_poll`? What is the assumption for a new loop implementation to work with PyZMQ?

**Comment by minrk** [comment]
> Q: Is there particular reasons to limit the support for different asyncio event loop implementations (e.g., uvloop)?

In pyzmq, yes, the reason I described above: to do so requires using the edge-triggered zmq.FD, which, having worked with in zmq.green, I don't want to use.

> Is it possible to plug-and-play different event loop implementations with zmq_poll? 

Not without modifying the underlying libzmq. If you modify libzmq to use a pluggable API, then this would be possible.
