### ISSUE TITLE
100% CPU usage with pyzmq socket when sending huge data.

### ISSUE THREAD

**Issue by thehackercat** [zeromq/pyzmq#887]
I am currently in the process of implementing a communication pipeline between several processes using pyzmq, all using the Push/Pull mechanism. I write a Pub/Sub pipeline to generate/receive tasks and a Push/Pull pipeline to send/get data and here is where my problem also starts: ZeroMQ seems to be using 100% CPU load when I am trying to send a huge xml data(size: 150MB, type: string) using `socket.send()`.

Here is the code in question, which attempts to send just one message:

``` python
# netengine.py
class NetEngine:
    """
    网络引擎
    """
    def __init__(self, _parser_ip, _push_port, _sub_port):
        # 初始化网络通道
        self.context = zmq.Context()
        self.sender = self.context.socket(zmq.PUSH)
        self.receiver = self.context.socket(zmq.SUB)
        self.parser_ip = _parser_ip
        self.push_port = _push_port
        self.sub_port = _sub_port
        self.messager = Message() # message analysiser

    def net_init(self):
        # 网络通道端口绑定
        self.sender.connect("tcp://%s:%s" % (self.parser_ip, self.push_port))
        self.receiver.connect("tcp://%s:%s" % (self.parser_ip, self.sub_port))

    def send_msg(self, str):
        self.sender.send(str)

    def on_recv(self, cmd):
        front_back_print("incomming event:{}".format(cmd))

    def net_loop(self):
        """
        开启网络循环,与分析端对接,登录并交换设备信息
        :return: void
        """
        front_back_print('Main runs as %s' % (os.getpid()))
        self.receiver.setsockopt(zmq.SUBSCRIBE, "UID_{}".format(uid))  # 订阅分析端发布消息的uid通道
        front_back_print('---- Sending login information ----')
        login_info = {'uid': uid, 'group_id': group_id, 'my_ip': host,
                      'role': device_role, 'type': device_type}  # 初始化login报文信息
        self.send_msg("{}".format(self.messager.buildMsg('login', login_info)))  # 发送login报文

        while True:
            """
            持续从分析端接收报文
            完成login握手
            """
            msg = self.receiver.recv().split(' ', 1)[1]
            cmd, msg_info = self.messager.parseMsg(msg)

            # 网络引擎处理login操作,其余报文交给event_exec()处理
            if cmd == 'login':
                # 分析端信息, 目前并不不会用到以下信息, 先注释掉了
                # _parser_uid = msg_info['uid']
                # _parser_group_id = msg_info['group_id']
                _parser_ip = msg_info['my_ip']
                _parser_device_role = msg_info['role']
                _parser_device_type = msg_info['type']

                front_back_print('Parser ip: ' + _parser_ip + ' & device_role: ' + _parser_device_role +
                                 ' & divice_type: ' + _parser_device_type)
                front_back_print('Login successfully!')
            else:
                self.on_recv(cmd)
                ee.event_exec(cmd, msg_info)  # 传给base插件进行业务处理

            time.sleep(1)

    def net_close(self):
        """
        关闭网络引擎接口
        :return: void
        """
        self.receiver.close()
        self.sender.close()
        self.context.term()

```

This is code of my net engine.

And when I run code as follow:

``` python
file = open(data_file)
content = file.read() # content is a HUGE xml data(size: 150MB, type: str)
file.close() 
net_engine.send_msg("{}".format(content)
```

CPU has rised to 100%.

And I cant figure out why.

Have I done something wrong? I am really confused!

**Comment by minrk** [comment]
It is probably useful to 

This line stands out to me:

```python
"{}".format(content)
```

That's building a new string, adding your `content` as part of it, but since there's nothing else in the format string, it is identical to the original. This is a very expensive way to copy a string, and you may not want the copy in the first place. Currently, your code will have at least three copies of the message in memory:

1. `content`
2. `"{}".format(content)`
3. a copy made by `send(str)`, which has the default argument `copy=True`

What you may want to do is make a non-copying send of the original content:

```python
send(content, copy=False)
```

This will send the content without making any extra in-memory copies.

I don't know for sure that's what is taking CPU, but it's the first thing that came to mind, given that your messages are large.

**Comment by thehackercat** [comment]
@minrk Thx.

I have tried your suggestion, but the CPU maintained at 100% still.

Though your suggestion didn't fix High CPU problem, It helped me  to optimize my code.

**Comment by massimiliano-della-rovere** [comment]
@thehackercat I think these points from http://zeromq.org/area:faq fit your case: 

**When sending a multipart message, my receiver doesn't get any message parts until the last part is sent. Is ZeroMQ broken?**

The ZeroMQ library guarantees that multipart messages are sent and received atomically. A message cannot be delivered by the library to your application until all frames have been received. Obviously, this cannot happen while the sender still has parts pending or in queue.

There are two reasons for multipart message support in the library.

This function supports a scatter/gather-style for message transmission so the application can avoid copying the (potentially) large data to a single message. Zero copy is a huge performance win particularly for large messages.
Multipart support may help a protocol designer to logically separate their protocol into separate frames at the application level. This may ease parsing on the receiving end since not all languages support fast bit-twiddling for binary structures like C.

**Does ZeroMQ buffer my entire message in memory before sending to its recipients?**

Yes. So if you are sending multi-gigabyte messages, it will consume RAM to store those messages on both sides. The memory on the sender side is freed after last part of the message has been sent. Also, see point above.

**Is it possible to receive EAGAIN or to block when sending a multi-part message?**

Multipart messages are sent as an atomic unit. If one part is sent successfully, then the socket is guaranteed to not block or return EAGAIN until all parts have been sent. Of course, if you run out of memory in the meantime then the guarantee doesn't mean much, so don't try to send messages that exceed available memory.

**Are you trying to tell me that ZeroMQ won't magically save me from out-of-memory conditions?**

You are a perfect candidate for using AMQP or JMS. Please use Google to find more information on libraries that support those platforms and protocols.
