### ISSUE TITLE
Support building against bundled libzmq for cython extensions?

### ISSUE THREAD

**Issue by alexrudy** [zeromq/pyzmq#903]
I'd like to build a cython extension against pyzmq. In order to do this portably, I'd like to be able to link against the bundled libzmq when it is present. I think that all I need to do this is to have a portable way to get the libzmq library path (like ``get_includes()``)  and to keep the bundled libzmq's header files somewhere sensible in pyzmq when it is bundled, adding that path to the output of ``get_includes``.

I'm happy to try implementing this, but I want to make sure there is not a good reason to avoid this.

This comes up for me a lot because pip defaults to installing bundled copies of libzmq, which then conflict with a system built libzmq, but that might be a harder issue to get around. (On my own machine, I can always do ``pip install --no-use-wheel pyzmq``, but I don't always have control over how pyzmq is installed.

**Comment by minrk** [comment]
You will have to be a little careful, because you are not guaranteed that libzmq is bundled, and pyzmq doesn't bundle libzmq's headers, and further *shouldn't* if libzmq is not bundled as an extension itself. So you will always have to cover both cases of bundled libzmq and non-bundled libzmq.

But in principle, adding the zmq headers when libzmq is bundled as an extension is sensible.

**Comment by alexrudy** [comment]
I will ensure that pyzmq won't bundle libzmq headers when libzmq is not bundled, and I'd prefer to reliably have unbundled versions, so I still think that should be the default. But I'll add the ability to include the libzmq headers when bundled.

**Comment by minrk** [comment]
Fixed by #905
