### ISSUE TITLE
Is using non bundled zeromq still supported on windows ?

### ISSUE THREAD

**Issue by cournape** [zeromq/pyzmq#934]
Hi,

While trying to update pyzmq to 16.0.0 (freom 15.2.0), I noticed that when using bundled zmq sources, pyzmq builds libzmq as a python extension. When using the `--zmq=<path to zmq lib>`, this extension is not built as expected, but  the `zmq.__init__` seems to assume `libzmq` to be available as a python extension, and otherwise does not load the dll at all, thus causing import failures.

If the intent is to still support this method, would it make sense to simply build that extension in both bundled and non bundle modes (in the non bundled mode, the extension would of course link to the externally provided zmq).

**Comment by minrk** [comment]
I don't think the extension has a non-bundled mode. Either there is a bundled Extension or there isn't an Extension. If zmq is external, the Extension is skipped.

I'm happy to support building with non-bundled windows zeromq, I just don't have any experience/expertise for maintaining it.

16.0 has some changes to simplify loading the bundled libzmq, I don't think it was intentional for this to result in breaking things. But now it makes sense that the switch to always `import _libzmq` would preclude that.

What would be 100% super awesome would be if someone could add an AppVeyor build that installs pyzmq with libzmq already on the system. That probably isn't going to be me, though.

**Comment by minrk** [comment]
dll bundling has changed and uses standard DLL loading thanks to delvewheel. No need for libzmq as an extension anymore, most of the time.
