### ISSUE TITLE
zmq.asyncio.Context.instance() may return a zmq.sugar.context.Context instance

### ISSUE THREAD

**Issue by tcwalther** [zeromq/pyzmq#940]
Calling `zmq.asyncio.Context.instance()` can return a context of a different type:

```python
import zmq.asyncio
context = zmq.asyncio.Context.instance()
assert isinstance(context, zmq.asyncio.Context)  # works fine
```

``` python
import zmq
context = zmq.Context.instance()
assert isinstance(context, zmq.sugar.context.Context)

import zmq.asyncio
context = zmq.asyncio.Context.instance()
# Error ahead:
assert isinstance(context, zmq.asyncio.Context), "context is of unexpected type {}".format(type(context))  
```

Is this intended?

**Comment by minrk** [comment]
That's probably not intended, but mixing zmq.Context and zmq.asyncio.Context is likely to get something into trouble.

**Comment by tcwalther** [comment]
I agree. One of my co-workers ran into this problem, and looking through his code, I couldn't find a single place where he calls `zmq.Context`, but he still ends up with a regular context somehow. The example above is merely the easiest way I could reproduce his bug.

This is my workaround right now:

```python
def _get_asyncio_context():
    context = zmq.asyncio.Context.instance()
    if not isinstance(context, zmq.asyncio.Context):
        context = zmq.asyncio.Context()
        zmq.asyncio.Context._instance = context
    return context
```

**Comment by schwingkopf** [comment]
Is there hope that this issue will be fixed at some point enabling to mixing zmq.Context and zmq.asyncio.Context? Or are there fundamental problems prohibiting this?

I have a particular case where the workaround from @tcwalther does not help: 
Using inproc communication between a zmq.sugar.socket.Socket and a zmq.asyncio.Socket. This fails since inproc requires both sockets to be created from the same underlying context instance.

This is useful when having async code alongside with a multitude of light-weight worker threads e.g.:
`import asyncio
from threading import Thread
import zmq
import zmq.asyncio

addr = "inproc://foo:9000"

def worker(worker_id):
    with zmq.Context.instance().socket(zmq.PUSH) as sock:
        sock.connect(addr)
        while True:
            sock.send_pyobj(f"Hello from sender {worker_id}")
            
async def receiver_async():
    with zmq.asyncio.Context.instance().socket(zmq.PULL) as sock:
        sock.bind(addr)
        while True:
            msg = await sock.recv_pyobj()
            print(msg)

ids = [1, 2, 3, 4]
threads = [Thread(target=worker, args=(id,)).start() for id in ids]

asyncio.get_event_loop().create_task(receiver_async())
asyncio.get_event_loop().run_forever()`

where the "receiver_async" might for example be used in an async webserver

Workarounds for this use case are:
1. Use 'tcp' instead of 'inproc' and the workaround above to ensure correct context types
2. Use async sockets everywhere, requiring to place an asyncio loop in each of the worker threads

I think both workarounds are not ideal and a solution within pyzmq would be nice.

**Comment by minrk** [comment]
@schwingkopf the obvious fix is for the second call to raise an error indicating that a different class is already registered for the instance. That's the most explicit, no guessing option. Another option I'm less fond of would be to make the same check and create a *second* context object in the event of a conflict. This would work in most cases, but inproc between two instances wouldn't work. A third option is to make incompatible classes use `shadow` as described in #1354, so that the *same* underlying context is used. I'm not sure that's the right approach, but it could be.

The above use case with mixing async and blocking sockets can currently be [addressed with `shadow`](https://github.com/zeromq/pyzmq/issues/1354#issuecomment-583740388):

```python
ctx = zmq.Context.instance()
actx = zmq.asyncio.Context.shadow(ctx.underlying)
```

though as I mentioned over there, I do think there's room for a better API for mixing async and blocking sockets. But at least shadow will work until that's figured out.
