### ISSUE TITLE
PUB/SUB + pyobj needs documentation

### ISSUE THREAD

**Issue by vladfi1** [zeromq/pyzmq#957]
I've been trying to transmit python objects using PUB/SUB and `[send/recv]_pyobj`. It turns out that this doesn't work out of the box, due to the way topics work with PUB/SUB. The subscriber needs to set a topic:

    socket.setsockopt_string(zmq.SUBSCRIBE, "")

and the publisher needs to send the topic as the first part of the message

    socket.send_string("", zmq.SNDMORE)
    socket.send_pyobj(data)

The subscriber will have to eat the topic with an extra receive:

    topic = socket.recv_string()
    data = socket.recv_pyobj()

It would be nice if this were better documented - both how to send topics with `send_pyobj`, and that the topic is absolutely necessary in the first place (if the topic isn't set on the subscriber side, no messages go through).

**Comment by minrk** [comment]
The way PUB/SUB works, subscribers start in a completely unsubscribed state. By subscribing to the empty topic `''`, you are subscribing to all topics. If you do this, the additional topic frame of `send(b'')` is unnecessary, and you can use single send/recv_pyobj calls. You only need a separate topic frame if you are actually using topics, rather than having all subscribers subscribe to all topics. This works, for instance:

```python
sub.subscribe(b'') # subscribe to all
pub.send_pyobj(data)
recvd_data = sub.recv_pyobj)
```

But as you've pointed out, if you have 'real' topics, the topic must be sent in a dedicated frame with `send(topic, SNDMORE)`. Most of this ought to be covered in [the zmq Guide](http://zguide.zeromq.org/py:all).

Indeed, the `send_<serialize>` and `recv_<deserialize>` map exactly to single `socket.send` and `socket.recv` calls, so all of the send/recv/SNDMORE/RCVMORE semantics are exactly the same, including the relationship to the topic frame. The only addition is a single serialize/deserialize call, for convenience.
