### ISSUE TITLE
Inconsistent data types for send in the api

### ISSUE THREAD

**Issue by subiol** [zeromq/pyzmq#980]
I am curious as to why the data types that the different zmq.send functions require are so different and I can not figure out the reason. As per the docs, zmq.send() requires data to be (object, str, Frame), then you have the function zmq.send_string() that requires the data to be a str (python3), but then zmq.send_multipart requires the data to be a list of (Frame, bytes, buffer-providers).

So send() accepts str but not bytes, then there is a method that accepts only str, and send_multipart() accepts bytes but not str. What is the reason for the api to be like this?

**Comment by minrk** [comment]
This is a typo in the `send` docstring, leftover from Python 2 days. It says `str`, but means `bytes`. Fixed by #981.

- `send` accepts anything that provides the buffer-API, which includes bytes objects, memoryviews, arrays, Frames, etc.. This notably does *not* include `str/unicode`.
- `send_multipart` calls `send` N times, so accepts a list of whatever `send` accepts.
- `send_string` is like `send_json` or `send_pyobj` in that it is a convenience method for sending an object that does *not* provide the buffer protocol (in this case, `str/unicode` objects).

**Comment by subiol** [comment]
@minrk not directly related but since you mention it:

> send_multipart calls send N times, so accepts a list of whatever send accepts.

If I am writting a program where latency is more important than throughput, does this mean that I would do better to not send the subscription system of send_multipart and always use send with the whole composed message? Does multisend actually sends each frame separately?

**Comment by minrk** [comment]
Frames of a multipart message are not sent separately, so the different between a single send and a multipart send is purely the number of local function calls. On the network, it makes no difference.
