### ISSUE TITLE
Will pyzmq fail in an MPI scenario?

### ISSUE THREAD

**Issue by cshanbo** [zeromq/pyzmq#984]
HI all,
I was using pyzmq and [mpi](https://www.open-mpi.org/) to build a multi-node(machine)/ multi-gpu deep learning project.
The code runs well in a single-node, multi-gpu scenario, while fails in the multi-node one.

It fails when the following `query` happens:
```
# definition
self.ccontext = zmq.Context()
self.csocket.bind('tcp://*:{}'.format(port)) 

# try
try:
    query = self.csocket.recv_json(flags=zmq.NOBLOCK)
except zmq.Again:  # if a query has not happened, try again
    continue
except zmq.ZMQError as exc:
    raise PlatoonError("while receiving using ZMQ socket", exc)

```

It keeps raising zmq.Again multiple time, and then fails (timeout). I'm not sure whether it is a pyzmq problem or something I mis-used (like using ipc instead of tcp?). Any advice is helpful.

Thank you

**Comment by minrk** [comment]
Can you provide a more complete code sample that shows the issue? I would expect recv(NOBLOCK) to raise Again most of the time (meaning there isn't a message waiting to be received). Do you want to wait for messages at all?

IPC is mostly for single-node communication. Are you using ipc across machines on a shared filesystem? I'm not sure if that works.

**Comment by tsirif** [comment]
We are using ipc for intranode communication and utilize MPI for internode collective operations.

The code lies [here](https://github.com/cshanbo/platoon/tree/fix/zmq_error).
Specifically, this is the [controller](https://github.com/cshanbo/platoon/blob/fix/zmq_error/platoon/channel/controller.py) and this is the [worker](https://github.com/cshanbo/platoon/blob/fix/zmq_error/platoon/channel/worker.py). Interface is explained [here](https://tsirif.github.io/cosa/multi-gpu-node-interface-in-platoon/) and probably the most depicting image is this:

![Deployment of Platoon](https://tsirif.github.io/images/platoon_architecture.png)

Connection is initialized [here](https://github.com/cshanbo/platoon/blob/fix/zmq_error/platoon/channel/controller.py#L324) for Controller and [here](https://github.com/cshanbo/platoon/blob/fix/zmq_error/platoon/channel/worker.py#L321) for Worker. Controller loops asking for children processes' status and polling socket in method "[serve](https://github.com/cshanbo/platoon/blob/fix/zmq_error/platoon/channel/controller.py#L260)".

**Comment by minrk** [comment]
This should work in principle. I don't see anything obviously wrong, but you might want to try a few things:

1. use DEALER/ROUTER instead of REQ/REP. REQ/REP sockets are generally not encouraged for production use as they don't handle disconnects or other changes well.
2. try `tcp` while getting started. `ipc` *should* work, but it can hide bugs (e.g. I think multiple sockets can try to bind on the same ipc socket, which will cause problems such as lost messages by whichever socket bound first). I think there can also be problems if sockets connect before bind with ipc, or multiple sockets try to bind on the same ipc socket, where tcp will generally work fine or raise appropriate errors, rather than silently failing like ipc.

**Comment by tsirif** [comment]
Thank you for answering!

I will try according to your suggestions and I will see. Q: Does ipc have
speed advantages over tcp intranode-ly?

**Comment by minrk** [comment]
loopback's generally pretty quick. I'm not sure if ipc has much of an advantage.
